### ISSUE TITLE
Resources (e.g. CSS) in sub-folders don't seem to work

### ISSUE THREAD

**Issue by Eilon** [xamarin/MobileBlazorBindings#103]
Original report: https://github.com/xamarin/MobileBlazorBindings/issues/102

From @bryanp-ramosoil :
> Perfect thanks. I don't know if this is an issue but it only seems to work if the css file is the root of the application. I've attempted to put the file in an Assets folder then reference it using it's name space and it fails. I've used a decompiler to verify the resource was there and it was.
> 
> Fails
Example: MyProject.Assets.styles.css
Folder: root/Assets/styles.css
> 
> Works
Example: styles.css
Folder: root/styles.css
> 
> It's not a deal breaker but I thought I would pass the information along.
> 
> Thank you for creating this project. This is perfect for us web developers who now need to start building mobile apps.

**Comment by Eilon** [comment]
OK this took an almost embarassingly long time to figure out, and it turns out the way to do this is just _too_ easy. Instead of using the resource _ID_, you should use the resource _path_!

That is, if your asset is in the folder `Assets/styles.css`, then the path is just `Assets/styles.css`! The internal Xamarin.Forms stuff will later process that and find the resource ID, as seen [here](https://github.com/xamarin/Xamarin.Forms/blob/26584c588e993c1f241fd9c41fa1ae7d74a1394f/Xamarin.Forms.Core/Xaml/XamlResourceIdAttribute.cs#L40-L47). It does this via an assembly-level attribute that it adds to the generated code automatically, such as:

```c#
// auto-generated by Xamarin.Forms build
[assembly: XamlResourceId("MobileBlazorBindingsWeather.style_assets.WeatherStyles.css", "style-assets/WeatherStyles.css", null)]
```

**Comment by Eilon** [comment]
I will update docs on CSS to include info on this too.

**Comment by bryanp-ramosoil** [comment]
It’s so simple and totally makes sense. Thank you for the update!.

**Comment by Eilon** [comment]
Here are the updated docs on CSS: https://docs.microsoft.com/en-us/mobile-blazor-bindings/ui/css-styles

Please log a new issue here if you have any additional feedback on this. Thank you!
