### ISSUE TITLE
Connect to MS SQL Database

### ISSUE THREAD

**Issue by Pipsy100** [xamarin/MobileBlazorBindings#105]
Is it possible to connect to a MS SQL Database with MobileBlazorBindings?

**Comment by Eilon** [comment]
It's perhaps possible but it's probably not a common pattern to do that. Communicating with a remote database directly from a mobile app is not a common pattern I've seen.

I would instead recommend one of these two patterns:

1. Have an intermediate layer (middle tier) for connecting to the database. This could be an HTTP web service, gRPC, or whatever other protocol that makes sense in your scenario.
2. If you want a local database, the full Todo App sample shows how to use SQLite: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoItemDatabase.cs

Please let me know if this answer is helpful.

**Comment by Pipsy100** [comment]
Hello Eilon,

I am running this code on a razor page

    protected override async Task OnInitializedAsync()
    {
        await load();
    }


    protected async Task load()
    {

        sponsors = await SponsorService.GetSponsorsAsync();
    }


It calls this service:

    public class SponsorService
    {
        string baseUrl = "https://sponsorapi.azurewebsites.net/";

        public async Task<Sponsor[]> GetSponsorsAsync()
        {
            HttpClient http = new HttpClient();
            var json = await http.GetStringAsync($"{baseUrl}api/sponsors");
            return JsonConvert.DeserializeObject<Sponsor[]>(json);
        }

}

But when I start the application I am getting this message:

I/Choreographer(15559): Skipped 76 frames!  The application may be doing too much work on its main thread.

Is there something wrong with my code?

Is there a forum or channel where you can post problems you have with Blazor or BlazorMobileBindings?

Thanx a lot.

Willem


Van: Eilon Lipton <notifications@github.com>
Verzonden: zondag 5 april 2020 0:21
Aan: xamarin/MobileBlazorBindings <MobileBlazorBindings@noreply.github.com>
CC: Pipsy100 <w_hoogland@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [xamarin/MobileBlazorBindings] Connect to MS SQL Database (#105)


It's perhaps possible but it's probably not a common pattern to do that. Communicating with a remote database directly from a mobile app is not a common pattern I've seen.

I would instead recommend one of these two patterns:

  1.  Have an intermediate layer (middle tier) for connecting to the database. This could be an HTTP web service, gRPC, or whatever other protocol that makes sense in your scenario.
  2.  If you want a local database, the full Todo App sample shows how to use SQLite: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoItemDatabase.cs

Please let me know if this answer is helpful.

**Comment by Eilon** [comment]
Hi @Pipsy100 sorry for the delay.

I haven't seen that problem or error before. This looks very similar to the pattern that the TodoApp sample uses [here](https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoList.razor#L57-L62) to load items at startup.

Is there a chance that the service is returning so much data that it's taking a long time to do the JSON deserialization? That's the only synchronous (blocking) code that I see in the app. Also worth asking: does the app have any noticable delay? Maybe that warning from the Choreographer can be ignored? (It isn't necessarily a bad problem, I believe it just means some animations might be not as nice.)
