### ISSUE TITLE
Thread Issue

### ISSUE THREAD

**Issue by Pipsy100** [xamarin/MobileBlazorBindings#108]
I am running this code on a razor page

    protected override async Task OnInitializedAsync()
    {
        await load();
    }

    protected async Task load()
    {

        sponsors = await SponsorService.GetSponsorsAsync();
    }

It calls this service:

    public class SponsorService
    {
        string baseUrl = "https://sponsorapi.azurewebsites.net/";

        public async Task<Sponsor[]> GetSponsorsAsync()
        {
            HttpClient http = new HttpClient();
            var json = await http.GetStringAsync($"{baseUrl}api/sponsors");
            return JsonConvert.DeserializeObject<Sponsor[]>(json);
        }

}

But when I start the application I am getting this message:

I/Choreographer(15559): Skipped 76 frames!  The application may be doing too much work on its main thread.

Is there something wrong with my code?

**Comment by Eilon** [comment]
Hi @Pipsy100 , I'm not sure how I missed this issue, but here I am.

One of the top hits for this type of issue is this post on StackOverflow: https://stackoverflow.com/questions/14678593/the-application-may-be-doing-too-much-work-on-its-main-thread

And based on what I've read there, skipping ~76 frames while running in an Emulator is not necessarily something to worry about. It also depends exactly when you see this message. It's not necessarily while you're doing InitializeAsync work, but it could be. Hard to tell.

In your case if you see a noticable delay, you could consider not doing this work in OnInitializedAsync, and instead spawn a background task to load the data while the UI shows a loading UI. Then when the background task completes, you can update the UI very quickly with the data.

Beyond this, one feature that Mobile Blazor Bindings doesn't yet have is an easy way to have "virtualized lists." That is, UI controls that load only the data that is currently visible to the user.
