### ISSUE TITLE
[Question] Is it possible to use native Blazor syntax within Mobile Bindings ?

### ISSUE THREAD

**Issue by redradist** [xamarin/MobileBlazorBindings#114]
What about writing general **Blazor** code within basic **html** and calling platform **API**:

```razor
@page "/counter"

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount += 2;
    }

    private CallSystemAPI()
    {
        #ifdef Android
            // Some system API call via service or direct call
        #endif
    }
}
```

Will it be possible ?
Technically it is possible to do with **WebView** on **Android** and **iOS**

Also it would be nice to share in one **Blazor** file **native** and **html** component ...
```razor
@page "/counter"

<h1>Counter</h1>

<Label FontSize="30"
           Text="@("You pressed " + currentCount + " times")" />
<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount += 2;
    }

    private CallSystemAPI()
    {
        #ifdef Android
            // Some system API call via service or direct call
        #endif
    }
}
```
It could be done by adding for specific **Xamarin.Forms** component **Web Renderer** that will convert component to **html** elements or draw this component on **canvas** or **svg** element

In such way it would be possible to share UI completely between **Desktop** and **Web** !!

**Comment by Eilon** [comment]
We have some experiments around this exact idea! Stay tuned and I will post an update when we have something to share.

**Comment by redradist** [comment]
@Eilon 
> 
> We have some experiments around this exact idea! Stay tuned and I will post an update when we have something to share.

Nice to here !!
Do you have particular branch with this experiments ?

**Comment by Eilon** [comment]
No code to share right now, but we're working on a plan to have that out very soon!

**Comment by redradist** [comment]
@Eilon 
> 
> No code to share right now, but we're working on a plan to have that out very soon!

It would be exciting to test it !!
Okay, I'll be waiting ;)

**Comment by Eilon** [comment]
Sounds great, looking forward to hear your thoughts once it's available!

**Comment by redradist** [comment]
@Eilon 

Useful link with existing implementation of embedding Blazor in WebView using Xamarin.Forms !!
Exactly what I wanted ;)

I wish we would have the same with standard framework support )

**Comment by Eilon** [comment]
Very interesting project. We are working on cooking up something interesting as well. Battling some Android issues right now. Sounds like a plot to a sci-fi movie!

**Comment by Eilon** [comment]
Closing this issue in favor of https://github.com/xamarin/MobileBlazorBindings/issues/121, which tracks this feature now existing!
