### ISSUE TITLE
Redirect to another razor page

### ISSUE THREAD

**Issue by Tushar5292** [xamarin/MobileBlazorBindings#116]
Hi @Eilon , how to call or redirect to another razor page in Blazor?
I stocked @ this point.Could you pls.help me out.

**Comment by rohanbojja** [comment]
I don't think there's a navigation system at this point. You can use the Xamarin.Forms Shell Navigation. 

Check out this post,
https://chrissainty.com/mobile-blazor-bindings-xamarin-essentials/

**Comment by Eilon** [comment]
The closest thing that currently exists is the `ModalContainer` component. I previously wrote a little bit about it here: https://github.com/xamarin/MobileBlazorBindings/issues/89
