### ISSUE TITLE
Hybrid webview support ?

### ISSUE THREAD

**Issue by vd3d** [xamarin/MobileBlazorBindings#119]
Hi,

I have a blazor application, but this one is mixed with pure HTML & Javascript code.

I wish to have a mobile application, only change some stuffs, like the application bar etc... without redeveloping the whole application ?

So, is it possible to embed my WEB application into a webview with MobileBlazorBindings ?
(Or should I use Xamarin and/or a project like this one : https://github.com/xamarin/PortableRazor)

Thanks

**Comment by Eilon** [comment]
Hi @vd3d we're looking at some options for this type of app. Stay tuned here and I will post an update when we have something to share!

**Comment by Eilon** [comment]
cc @SteveSandersonMS

**Comment by redradist** [comment]
Guys, there is already exsiting implementation with Embedding Blazor to Mobile:

**Comment by Eilon** [comment]
Very interesting project. We are working on cooking up something interesting as well. Battling some Android issues right now. Sounds like a plot to a sci-fi movie!

**Comment by Eilon** [comment]
Closing this issue in favor of https://github.com/xamarin/MobileBlazorBindings/issues/121, which tracks this feature now existing!
