### ISSUE TITLE
MessageApp sample always shows the same email

### ISSUE THREAD

**Issue by Eilon** [xamarin/MobileBlazorBindings#127]
---
**Issue moved from SteveSandersonMS/BlazorOnXamarinFormsTest#5**
- Please respond to @Eilon.

---

_From @Eilon on Tuesday, June 23, 2020 6:40:25 AM_

Whatever the first "email" you click on is, it always shows that same email even if you click on another email.

**Comment by Eilon** [comment]
Works on Windows (WPF).

Doesn't work iOS or Android.

On the non-working platforms the Blazor hosting content at `0.0.0.0` is being loaded again, causing the page to show up empty.

On the working platform the Blazor hosting content is loaded only the first time the web view is visible.

**Comment by jspuij** [comment]
https://github.com/xamarin/MobileBlazorBindings/commit/b062f7e6008312d06aae1ec428862e5144f2b247#diff-2003c256a32bd8a1f565f12b30338851e78984c6279ee256b97294adfeab18fdR17-R20
