### ISSUE TITLE
is there a sample with a shell component anywhere?

### ISSUE THREAD

**Issue by aktxyz** [xamarin/MobileBlazorBindings#135]

**Comment by aktxyz** [comment]
whoops found it !

**Comment by Eilon** [comment]
For anyone else looking, the Shell sample is here: https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/MobileBlazorBindingsXaminals/MobileBlazorBindingsXaminals

However, there are currently many limitations with it so not everything works.

Here's the issue tracking Shell support: https://github.com/xamarin/MobileBlazorBindings/issues/11
