### ISSUE TITLE
limitations and structure request

### ISSUE THREAD

**Issue by aktxyz** [xamarin/MobileBlazorBindings#136]
Hi Eilon ... you are probably super busy on the new preview 4 !

When you get a chance, would it is possible to do a blurb or post on 2 things ...

- what are the current limitations (ie things you can do in Xamarin forms that you cannot do here), you mentioning limitations with shell is what made me think of this, its hard to know those limitations until you bump into them

- somehow describe the code structure and how things work, basically to make it easier for others to grok how things work and perhaps contribute

**Comment by Eilon** [comment]
Hi @aktxyz , thanks for checking out this project!

For your first question:

* If you divide Xamarin.Forms into two parts, this is my answer:
   1. The UI-specific features, such as the controls, opening dialogs, etc.
      * These are best tracked here: https://github.com/xamarin/MobileBlazorBindings/issues/5
   1. Everything not UI-specific, such as integrating with the device platform, doing background tasks, etc.
      * Just about everything should just work, because Mobile Blazor Bindings is all about writing UI. If it's not UI, it's no different.

For your second question:

I'll look at adding some docs to the repo that help show where to look for key sections. But there's just too much to go into any deep detail and it often changes, meaning a detailed doc would become stale very quickly.

But, for anyone looking to contribute, I recommend the following:

1. Look for open issues and see if you want to try to build or fix something. If so, just ask for help, and I will do my best (or someone else)!
1. If you want something that isn't already tracked, log a new issue, and I will be happy to help
1. Not all contributions are code contributions. Contributions can be:
   * Log a new issue with your feature request or bug report. These can help many other users by attracting attention to things.
   * Help repro existing bugs (or confirm that they don't repro)
   * Write a blog post or sample and share with the world!

Those are just a few ideas that come to mind.
