### ISSUE TITLE
Windows BlazorWebView: component's initial size is incorrect

### ISSUE THREAD

**Issue by Eilon** [xamarin/MobileBlazorBindings#137]
In the default template, run the Windows app. The BlazorWebView will have a "default" initial size instead of filling the bottom of the page.

If you resize the window, the WebView will snap back to the correct dimensions.

**Comment by jspuij** [comment]
Ha, my BWV had the same problem. I cannot remember how I've fixed it though. I'll look at the code and see whether I can find it.

**Comment by Eilon** [comment]
I know it was working at _some_ point. But then something must have regressed it. It could even be the update we made to WebView2 official maybe?

**Comment by Eilon** [comment]
This appears to be a High DPI problem because I'm running at 200% and the controls all show up as exactly 50% size.

![image](https://user-images.githubusercontent.com/202643/88220409-c9318000-cc17-11ea-9591-7098e937a955.png)

**Comment by Eilon** [comment]
Per @jspuij , this might be an issue with WebView2 itself: https://github.com/MicrosoftEdge/WebViewFeedback/issues/58#issuecomment-662675693

**Comment by Eilon** [comment]
Templates are updated with manifests as well: https://github.com/xamarin/MobileBlazorBindings/commit/9382181135c65be4641d528f0f9f27060438f8bd
