### ISSUE TITLE
Hybrid : how to use an existing Blazor app

### ISSUE THREAD

**Issue by vd3d** [xamarin/MobileBlazorBindings#146]
Hi,

I have an existing Blazor Web Application and I wish to keep the web version, but also build a mobile version, with the same code base.

I have created a fresh new project for the mobile (I just follow your instructions), but once I add a reference to the blazer (.NET 3.1) project, I have the following message:

> Error Project '..\Web.csproj' targets 'netcoreapp3.1'. It cannot be referenced by a project that targets '.NETStandard,Version=v2.0'.		C:\Program Files (x86)\Microsoft VisualStudio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	1655

Also, is there an existing way to communicate between Xamarin and the Blazor app (in both directions).
By example, the web app request geolocation information, and I wish to call to Xamarin geoloc (and not the webview one).

Thanks

**Comment by Eilon** [comment]
Hi @vd3d that's something we'll be working on in this milestone. We have a general issue for this logged here: https://github.com/xamarin/MobileBlazorBindings/issues/129

For right now you could probably make _some_ scenarios work, but until we have official support for it, there are probably several things that won't work.

For the other part of your question: The general way to do that would be using dependency injection. Each of your host apps (one for ASP.NET Core + Blazor, and one for Mobile Blazor Bindings) would implement some service that you define, such as `IMyGeoLocator`, and you'd use `@inject` to get an instance of your service in your app. Then the same code can use the interface and it will do the most efficient call depending on where it's running. You can learn more about using dependency injection in Mobile Blazor Bindings in the [Dependency Injection docs topic](https://docs.microsoft.com/mobile-blazor-bindings/advanced/dependency-injection).

**Comment by vd3d** [comment]
Thanks a lot Eilon,

It is the answer I expected :-P  ... but so, if you need to test a real production application ... just let me know, it can be a hard test case to prove the concept.

BTW, great job ;-)

**Comment by Eilon** [comment]
@vd3d I added a mention of this to #129:

https://github.com/xamarin/MobileBlazorBindings/issues/129#issuecomment-663654610

Thanks!
