### ISSUE TITLE
Publish on the app store iOS and Android

### ISSUE THREAD

**Issue by Ponant** [xamarin/MobileBlazorBindings#148]
We have a background in .Net Core and UWP apps and now we are building a mobile app for ios and android.
So we went directly to Xamarin as a first approach, but I just realized the progress in blazor, so given our background the choice of mobileblazorbindings is immediate!  👍 👍 👍 
Does anyone knows if an app using blazor bindings, mixing xamarin xaml and blazor syntax can be published on the stores for ios and android, or will there be any rejection during the publication process owing to the way the app is built? I do not expect it, but I prefer to ask before on-boarding.
In any case, I have a big thumbs up for this project!

**Comment by Eilon** [comment]
@Ponant though I haven't tried it (I don't have dev accounts for the Google Play Store of Apple App Store - yet!), any app build with Mobile Blazor Bindings is in effect "just a regular" Xamarin app. So, as long as you follow the steps for publishing a Xamarin app to an app store, it should be all the same.

Here is some more info:

* Publish to Apple App Store: https://docs.microsoft.com/xamarin/ios/deploy-test/app-distribution/
* Publish to Google Play Store: https://docs.microsoft.com/xamarin/android/deploy-test/publishing/publishing-to-google-play/

And there is a lot more info on those docs site if you look around.
