### ISSUE TITLE
Multiple BlazorWebView possible?

### ISSUE THREAD

**Issue by kestlerio** [xamarin/MobileBlazorBindings#149]
Is it possible to have more than one BlazorWebView in the whole window? And how does e.g. routing work then?

**Comment by Eilon** [comment]
Yes, absolutely you can have as many BlazorWebViews as you need!

We even have a sample app for it: https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/HybridMessageApp

This app happens to use XAML to be the native UI, and then uses BlazorWebViews here:

1. One to host a message list in the left pane:
   * BlazorWebView: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/HybridMessageApp/HybridMessageApp/MainPage.xaml#L17
   * Web contents: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/HybridMessageApp/HybridMessageApp/WebUI/FolderList.razor
1. And one to host the message list and details in the right pane:
   * BlazorWebView: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/HybridMessageApp/HybridMessageApp/MessageListPage.xaml#L13
   * Web contents: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/HybridMessageApp/HybridMessageApp/WebUI/MessageList.razor

I believe each BlazorWebView uses its own navigation but to be honest I'm not 100% sure. Either way, this is a scenario that we're planning to significantly improve, so if you have more thoughts on it, please let us know!
