### ISSUE TITLE
Blazor Web View Access native code delegates?

### ISSUE THREAD

**Issue by jhancock4d** [xamarin/MobileBlazorBindings#154]
Can Blazor Web View access Xamarin shared code for platform specifics? I.e. can I get access to NFC, Bluetooth, etc? It would be really great if I could load any of those libraries in to Xamarin and be able to call in and get events from them in Blazor Web View.

**Comment by Eilon** [comment]
YES! _All_ the .NET code running in a Mobile Blazor Bindings app, including from the "web" part of a Hybrid Blazor app, can access all the exact same functions that any Xamarin.Forms app can access. As long as the functionality you want exists in Xamarin, you can call it exactly the same way in Mobile Blazor Bindings. (And even if it isn't directly available, Xamarin has APIs to let you call it anyway into native iOS, Android, etc.).

**Comment by ozzioma** [comment]
Just stumbled on this.
@Eilon could you please clarify if it's possible to use Xamarin Essentials code from a Blazor component/page?

I mean say I have a Blazor page ("/customer/create") and I want to access say the geolocation, file picker etc native device libs from Xamarin Essentials?
Can I use them from the Blazor page? That is a plain html/css/js Blazor page hosted in a WebView and does not contain any native components?

Like so 


```
@using Xamarin.Essentials

<button class="btn btn-primary" @onclick="TakePhotoAsync">
Take Photo
</button>

@code
{

async Task TakePhotoAsync()
{
    try
    {
        var photo = await MediaPicker.CapturePhotoAsync();
        await LoadPhotoAsync(photo);
        Console.WriteLine($"CapturePhotoAsync COMPLETED: {PhotoPath}");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"CapturePhotoAsync THREW: {ex.Message}");
    }
}

async Task LoadPhotoAsync(FileResult photo)
{
    // canceled
    if (photo == null)
    {
        PhotoPath = null;
        return;
    }
    // save the file into local storage
    var newFile = Path.Combine(FileSystem.CacheDirectory, photo.FileName);
    using (var stream = await photo.OpenReadAsync())
    using (var newStream = File.OpenWrite(newFile))
        await stream.CopyToAsync(newStream);

    PhotoPath = newFile;
}

```
Thanks

**Comment by Eilon** [comment]
Yes this should totally work!

**Comment by ozzioma** [comment]
Awesome! Tried it and it worked! 
To think I held off adopting MBB cos of my not being sure this would work!
Thanks for the great work!

A few questions though.
MBB ha given me 2 solid models for developing mobile apps, being firstly a workable replacement for Ionic, namely

1. A server side hosted Blazor WebAssembly app hosted on some server and served within a WebView component
2. Hybrid MBB.

In terms of security, performance and OTA updates, would it be possible to recommend one over the other based on what considerations?
I need this to pitch to my team.

Thanks

**Comment by Eilon** [comment]
First, please keep in mind that this is an _experimental_ project with no particular release plan, EXCEPT that we are working to productize the BlazorWebView component for Windows and macOS in .NET 6 (RTM later this year 2021): https://github.com/dotnet/aspnetcore/issues/27217

But to your specific questions:

With MBB _all_ of your .NET code runs locally on the device/desktop. There is no web server involved and no HTTP to make web requests. The native and HTML Razor views all run locally. This has an advantage of working 100% offline in all conditions. Obviously you can check if there is network available to make remote API calls, etc. You also get 100% access to the device's functionality from anywhere in the code. Using sensors, storage, devices, etc. is all possible as long as the platform allows it.

So the choice between different ways of developing the app depend a lot on what your requirements are. The good news is that whatever your requirements are, there's a way to use Blazor to build the app!

**Comment by ozzioma** [comment]
Thanks for the feedback!

How about security/authentication/OIDC and session state management?
Been going through the docs and issues, still no clue how to get it working with MBB.
Any pointers?

Thanks

**Comment by Eilon** [comment]
Hi @ozzioma the simplest thing I can say about auth is that it... isn't simple 😄 

But we have 3 samples that show how to do auth in native and hybrid apps with Mobile Blazor Bindings:

1. Hybrid App auth (OIDC): https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/HybridAuthSample
2. Hybrid App auth using MSAL (e.g. Azure AD): https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/HybridMsalAuthSample
3. Native App auth: https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/MobileBlazorBindingsAuthSample

I suggest trying those samples out to see how they work and then adapting to your needs.

**Comment by ozzioma** [comment]
Thanks again!
Will check out the examples.

I'm going to assume manual auth/login also works fine for MBB. Like this snippet below


```
 var claims = new List<Claim>();
                            claims.Add(new Claim(ClaimTypes.Email, fullName));
                            claims.Add(new Claim(ClaimTypes.Name, Input.Email));

var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                            var authProperties = new AuthenticationProperties
                            {
                                IsPersistent = Input.RememberMe,
                                RedirectUri = this.Request.Host.Value
                            };

                            _logger.LogInformation("Signing in the user");

                            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                            new ClaimsPrincipal(claimsIdentity), authProperties);

```

My auth workflow includes a mix of OIDC, manual login for some apps and mandatory OTP verification.
Would appreciate clarifications how all that is supposed to work within the context of MBB.

Thanks

**Comment by Eilon** [comment]
Hi @ozzioma I am not an auth expert but there are certain things that will be different between MBB and other Blazor Apps. One big difference is that on mobile platforms such as iOS and Android there are usually Store requirements that auth take place in a secure browser popup and not in a regular embedded WebView (in part to ensure that the app can't steal credentials). If you have some specific questions or thoughts on auth in MBB then I recommend logging a new issue for that and we can get the right auth experts involved to help out.

**Comment by dcuccia** [comment]
I'd also support the new issue to get some auth expert guidance, very relevant for my scenario as well.

**Comment by sabitertan** [comment]
@ozzioma , @dcuccia I didn't try with latest MBB but this may help too: https://github.com/WildGums/Blorc.OpenIdConnect
