### ISSUE TITLE
Hybrid App Fails On Startup (Mac)

### ISSUE THREAD

**Issue by lmf-git** [xamarin/MobileBlazorBindings#159]
Mobile bindings project template works the hybrid doesn't, the error looks like it is Windows dependency related but I've had VS Code (Full) for a few days so I'd take it with a grain of salt.

"Experimental Mobile Blazor Bindings App" works perfectly

Hybrid template causes below errors (started focusing on running iOS and most native first)

![nsa-superfluous](https://user-images.githubusercontent.com/67340984/89114901-1bc13680-d479-11ea-8267-34094cd203a4.png)
![gchq-extra](https://user-images.githubusercontent.com/67340984/89114903-25e33500-d479-11ea-8ad4-c1d89e8a14ce.png)

**Comment by Eilon** [comment]
Hi @lmf-git , sorry you're running into this problem. If you're running this on a Mac, right-click on the `MyApp.Windows` project and select Unload Project (or delete the project). As of now, the Windows projects are not buildable on Mac and they cause this problem. There is a note on this in the [Release Notes](https://github.com/xamarin/MobileBlazorBindings/issues/134) if you want to have a look and see other notes.

If you want to create a new solution from scratch without the Windows project, you can run this command:

```shell
dotnet new blazorhybrid --CreateWindowsProject false -o AppWithoutWindows
```

And you can learn more about the template options in the docs: https://docs.microsoft.com/mobile-blazor-bindings/advanced/template-options#choose-which-platform-projects-to-create

Please let me know if I can help any further!

**Comment by lmf-git** [comment]
Thank you so much Elion! I love your videos and online presence, I'm not a Microsoft or dotnet guy but I really appreciate what you're doing.

**Comment by lmf-git** [comment]
Thank you!!!!!
![Screenshot 2020-08-03 at 17 57 12](https://user-images.githubusercontent.com/67340984/89207522-c8eb9a00-d5b2-11ea-9708-10f288026257.png)

Confirm works, also you are welcome to join our community if you wish but use a pseudonym or they'll all be begging you. I get 15-20 programmers a day asking me random questions lol. 
https://discord.gg/TfuxZ7

**Comment by Eilon** [comment]
Woohoo, so happy you got it working! I'd love to see what you build with Mobile Blazor Bindings!

**Comment by lmf-git** [comment]
Just something for a client, between me and you I've never touched C# before so it may be the first popular app made by a fool. :D

Thank you, I realise you are a very busy person. Take care! Thank you!

**Comment by Eilon** [comment]
Good stuff, good luck with your project!
