### ISSUE TITLE
Mobile blazor cannot use third-party blazor components

### ISSUE THREAD

**Issue by hw72869951** [xamarin/MobileBlazorBindings#160]

**Comment by yuhongw** [comment]
Probably caused by JSRuntime. Please see #150 IJSRuntime injection as web-specific service and this [commit ](https://github.com/soags/MobileBlazorBindings/commit/7abd02fe816869daee9f3915c2923c8b4199e18e)

**Comment by Eilon** [comment]
Original title: `Mobile blazor无法使用第三方blazor组件`
Translated title: `Mobile blazor cannot use third-party blazor components`

**Comment by arivera12** [comment]
This is related to https://github.com/xamarin/MobileBlazorBindings/issues/150

**Comment by Eilon** [comment]
@arivera12 yes this seems likely. Without further info in this issue I think that's the assumption I will make, so I'm closing this issue. Thank you again for your assistance with these issues!
