### ISSUE TITLE
Xamarin.Forms CollectionView Support in Mobile Blazor Bindings

### ISSUE THREAD

**Issue by rajeshjha96** [xamarin/MobileBlazorBindings#161]
We want to create some projects using the Mobile Blazor Bindings. But the unavailability Xamarin.Forms CollectionView or similar UI Control is stopping us.
 
This is the most useful UI Control in the xamarin forms toolkit. It is used for  presenting lists of data using different layout specifications. Kindly port this UI Control to the Mobile Blazor Bindings.

**Comment by Eilon** [comment]
Hi @rajeshjha96 , indeed adding support for templates controls such as CollectionView would be very useful. We have an issue on that logged here: https://github.com/xamarin/MobileBlazorBindings/issues/67 . Feel free to up-vote that issue so we can take that into account when prioritizing features. Thank you!
