### ISSUE TITLE
How to implement @onclick handler for StackLayout element?

### ISSUE THREAD

**Issue by eyupalemdar** [xamarin/MobileBlazorBindings#164]
Hi,

I was playing around with the MobileBlazorBindings and came to this so far. Here is my sample code:

```
<StackLayout>
    <Image Source="{ url binded }"  />
    <Label Text="{ text binded }" />
</StackLayout>
```
I want to add an "@onclick" handler to "StackLayout" element to do some action like "opening a container". Actually I wish to add "@onclick" handler to anything not just "StackLayout". 

Is there a way to do this or am I missing something?

Best regards.

**Comment by Eilon** [comment]
Hi @eyupalemdar that's a great question! This is normally done using a feature called Gesture Recognizers in Xamarin.Forms. Unfortunately there isn't _great_ support for is in Mobile Blazor Bindings just yet, but it's something we definitely want to add.

In the meantime there are a few workarounds:

1. You could manually wire up Gesture Recognizers. Learn more about them in the Xamarin.Forms docs: https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/gestures/tap
  * You'll need access to the underyling Xamarin.Forms control in Mobile Blazor Bindings, which you can learn about here: https://docs.microsoft.com/mobile-blazor-bindings/advanced/access-native-controls
1. You could place the controls in a `<Grid>` and overlay an invisible grid cell on top of those controls that accepted clicks. One of our samples shows how to do this here:
   * https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsXaminals/MobileBlazorBindingsXaminals/Views/AnimalTemplate.razor#L19-L23
   * Note: This sample uses the NEW grid syntax. If you're using Preview 4 (the current release), you'll need to use the OLD grid syntax. Learn more about that in #139 

Please let me know if this helps you out!

**Comment by eyupalemdar** [comment]
Hi @Eilon, thank you very much for your quick response. 

Accessing native control is seems to be a practical solution for now. I am going to try it and I will inform you about the results.

**Comment by Eilon** [comment]
There is now a built-in way to do this with gesture support! It will be available in Preview 5, or you can use the [nightly feed](https://docs.microsoft.com/mobile-blazor-bindings/contribute/nightly-builds) to try it sooner.

Inside your `StackLayout` place a `TapGestureRecognizer` and hook up its `OnTapped` event.

Here's what it looks like:

```xml
    <StackLayout Margin="new Thickness(20)">

        <TapGestureRecognizer NumberOfTapsRequired="1" OnTapped="@OnStackLayoutTapped" />

        <Label Text="@($"The layout was clicked {count} times")" FontSize="20" BackgroundColor="Color.AliceBlue" />

    </StackLayout>
</ContentView>

@code
{
    int count;

    void OnStackLayoutTapped()
    {
        count += 1;
        StateHasChanged();
    }
```

**Comment by Eilon** [comment]
This was fixed in issue https://github.com/xamarin/MobileBlazorBindings/issues/165 by PR https://github.com/xamarin/MobileBlazorBindings/pull/166.

**Comment by eyupalemdar** [comment]
Hi @Eilon, it seems an elegant and blazor way solution. Nice job. I will check it out.
