### ISSUE TITLE
[Bug] HybridAppSample on Windows

### ISSUE THREAD

**Issue by LanceMcCarthy** [xamarin/MobileBlazorBindings#168]
If you build and deploy the `samples/HybridAppSample` with Windows as the startup project, you will get the following exception in the WebViewExtendedAnaheimRenderer at launch:

![image](https://user-images.githubusercontent.com/3520532/89906417-5d5c8a80-dbb9-11ea-9871-b99d10e6152c.png)

**Comment by Eilon** [comment]
Hmm, well that isn't supposed to happen! Can you confirm exactly which version/channel of Edge that you have? I believe it currently works only with Edge Canary Channel. Though, if that's what you have but there has been a recent update in the channel, it could explain the error.

**Comment by LanceMcCarthy** [comment]
Indeed, I'm running the Edge release channel  `Version 84.0.522.52 (Official build) (64-bit)`.

**Comment by Eilon** [comment]
I believe that at this time the WebView2 control, which is what Mobile Blazor Bindings uses on Windows, works only with Edge Canary Channel. The various Edge channels are all side-by-side, each with its own icon to run, so installing it shouldn't affect any other experiences on your machine. Can you try installing Edge Canary Channel and see if that fixes it for you?

**Comment by Eilon** [comment]
BTW I'm running `Version 86.0.605.0 (Official build) canary (64-bit)` and the HybridAppSample is working fine.

**Comment by Eilon** [comment]
And it just updated itself to `Version 86.0.606.0 (Official build) canary (64-bit)` and it still works.

**Comment by Eilon** [comment]
Closing because as far as I know this works as long as you're on Edge Canary. You can find all versions of Edge at this link: https://www.microsoftedgeinsider.com/download
