### ISSUE TITLE
BlazorWebView shows blank page with any new style

### ISSUE THREAD

**Issue by AmirImam** [xamarin/MobileBlazorBindings#176]
Hi
**BlazorWebView** works fine with the startup style, but when I try to set my own style it shows blank page, just white page without any elements.
I have removed **bootstrap.css** and **app.css** and set my css files.
I tried to remove all HTML in **MainLayout.razor**, and added just button, but also shows white page.
But when I set the original **bootstrap.css** and **app.css** it works

Note: My css is works fine on responsive mode in browser.

**Comment by Eilon** [comment]
Hi @AmirImam I'm sorry you're running into this issue. Can you show the code you have so that I can investigate? If you can upload your project to a GitHub repo that would make it easier to figure this out.

**Comment by AmirImam** [comment]
> Hi @AmirImam I'm sorry you're running into this issue. Can you show the code you have so that I can investigate? If you can upload your project to a GitHub repo that would make it easier to figure this out.

Thank you for your reply. 
[This is the project](https://github.com/AmirImam/BHybridSample)
It is just a sample. I am planning to create a full hybrid app without any XAML, just html in razor files, but of course I have stopped in first step

**Comment by AmirImam** [comment]
Any updates here?

**Comment by Eilon** [comment]
I am taking a look right now. I ran your code and I'm seeing the same result: a white window with nothing. I'll see what I can find out!

**Comment by Eilon** [comment]
Looks like this is the specific problem happening here:

```
System.InvalidOperationException
  Message=Cannot provide a value for property 'Js' on type 'BHybridSample.WebUI.Shared.NavMenu'. There is no registered service of type 'Microsoft.JSInterop.IJSRuntime'.
```

And it's happening in `WebUI/Shared/NavMenu.razor`:

```
@inject IJSRuntime Js;
```

**Comment by Eilon** [comment]
And it looks like we already have a request to solve this problem here: https://github.com/xamarin/MobileBlazorBindings/issues/150

So if you'd like, please add an up-vote to that issue and I'm closing this one.

**Comment by Eilon** [comment]
Oh, and as for the error not really showing up unless you set Catch All Exceptions, that's tracked here: https://github.com/xamarin/MobileBlazorBindings/issues/171
