### ISSUE TITLE
Website (SPA) using the WebUI?

### ISSUE THREAD

**Issue by vindberg** [xamarin/MobileBlazorBindings#177]
Hi, this is an interesting project. Finally we can reuse the webui on multiple platforms.

Would it also be possible to run a website version using the same webUI that is used for Andoid, iOS, etc.?

Best,
Anders

**Comment by Eilon** [comment]
Yes, that is the idea! But it depends on this issue, which is being worked on right now: https://github.com/xamarin/MobileBlazorBindings/issues/129

You'd be able to package up your web UI as a Razor Class Library (RCL), and then you would use that same RCL in your web app, and also in your Mobile Blazor Bindings Hybrid App inside a BlazorWebView.
