### ISSUE TITLE
[BUG] MainActivity.cs in Android project makes build fail randomly.

### ISSUE THREAD

**Issue by ktaze1** [xamarin/MobileBlazorBindings#182]
I do not know why and to be honest this just started to drove me crazy but sometimes I try to run the project everything randomly fails due to error: `'Resource.Layout' does not contain a definition for 'Tabbar'` and `Toolbar`. I have to rebuild the solution every time and hope it won't fail. Sometime it just runs, sometime it doesn't. What might cause this? I've have both API level 28 and 30 installed. My machine is Windows 10 and this happens in both VS 2019 and VS 2019 Preview.

Edit: upon further research, this problem has nothing to do with blazorbindings.

**Comment by Eilon** [comment]
Yes I get this sometimes too with Android. I think it has to do with the auto-generated Android resources file, which I think you need to remove from source control (it gets auto-generated on every build). And you are also correct that it isn't specifically related to Mobile Blazor Bindings. But it annoys me too!
