### ISSUE TITLE
Hope to support windows form as soon as possible

### ISSUE THREAD

**Issue by 199621616** [xamarin/MobileBlazorBindings#184]
We have a large number of traditional desktop windows form applications, mostly based on. Netframework 4.0 or earlier. They are in urgent need of modernization. Using mobile browser bingings to build hybrid applications is the most appropriate form of transformation at present.

Jspuij in https://jspuij.github.io/BlazorWebView.Docs/pages/index.html Consider adding windows form support. That's great. I hope it comes as soon as possible.

**Comment by 199621616** [comment]
One suggestion and two small problems found:
Suggestion: can the template be loaded by default Microsoft.Data.Sqlite As a unified storage method for mixed application data, there is a unified processing mechanism for the storage locations of database files. DB, webview2 data files, and common JSON files, or there are clear requirements for what restrictions.
Two small problems:
1、 Template generated Index.razor The code is anis. There is a garbled code in Chinese.
2 Index.razor When the height of the content exceeds the height of < div class = "content px-4" >, < div class = "top row px-4" > is blocked

**Comment by 199621616** [comment]
我们希望让用户了解最新版本更新动态，在WebUI/Pages文件夹下新建文件夹docs文件夹并添加Updater.razor文件，内容：
@page "/docs/updaters"
@using System.Text.Json
<br />
<h4 class="text-center">系统更新动态</h4>
<div class="table-responsive-lg">
    @if (lstItems is null)
    {
        <p><em>正在加载...</em></p>
    }
    else
    {
        <table class="table">
            @foreach (var xm in lstItems)
            {
                <tr class="table-success">
                    <td class="text-left">日期：@xm.update&nbsp; 版本号：<b>@xm.ver</b></td>
                </tr>
                <tr>
                    <td>
                        @xm.title
                    </td>
                </tr>
            }
    </table>
}

</div>


@code{
    private IList<dynamic> lstItems;

    protected override async Task OnInitializedAsync()
    {
        if (Microsoft.MobileBlazorBindings.WebView.BlazorHybridHost.TryGetEmbeddedResourceFile("\\docs\\updater.json", out var stream))
        {
            lstItems = await JsonSerializer.DeserializeAsync<IList<dynamic>>(stream, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        }
    }

}

更新内容构建于wwwroot/docs/updater.json中：
[
    {
      "update": "2020-09-25",
      "ver": "0.0.0",
      "title": "<ul><li>chiszs上线。</li></ul>"
    }
]


[Updaters.zip](https://github.com/xamarin/MobileBlazorBindings/files/5280737/Updaters.zip)
[Updater.zip](https://github.com/xamarin/MobileBlazorBindings/files/5280740/Updater.zip)

编译出现以下错误：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0656	缺少编译器要求的成员“Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create”	CHISZS	E:\公司软件50Blazor\CHISZS\CHISZS\WebUI\Pages\docs\Updaters.razor	16	活动

可是我没找到添加Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo的方法
我错过了什么？

**Comment by 199621616** [comment]
The deserialization of JSON files or webapi services is expected to support: List < dynamic >. Although strong typing has many advantages, list < dynamic > can save a lot of code and is very flexible, especially when dealing with complex systems

**Comment by Eilon** [comment]
Hi @199621616 thank you for checking out this project. Support for Windows Forms is not a primary goal right now but it's certainly something we can consider if there is enough demand for it (so far, you're the first person to ask about it).

For the other issues you describe:

1. Can you show what you're seeing with Index.razor problems with garbled text?
1. The Index.razor height issue I'm not familiar with. Can you share a sample app or screenshot that shows the problem?
1. Samples that use SQLite are available, such as the [Todo app sample](https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/MobileBlazorBindingsTodoSample) that uses [SQLite to store the "todo" items](https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoItemDatabase.cs#L18-L19)
1. For deserialization of JSON, I think I understand what you're talking about, but it isn't clear to me if you're saying there's a problem with it. If there is a problem, can you share more info so that we can investigate?

Thanks and I hope to hear from you soon!

**Comment by 199621616** [comment]
其它问题：
一、1= 模板生成的索引. razor 代码是 anis 。中文中有一个乱码。
重现方式：
1、dotnet new blazorhybrid -o FirstBlazorHybridApp
2、打开Index.razor，在<h1>Hello, world!</h1>处，增加一行
中文：<h1>你好，世界</h1>
3、按F5
出现：、
![image](https://user-images.githubusercontent.com/25498672/94337249-aa86a580-001b-11eb-81ee-93542a11653e.png)

**Comment by 199621616** [comment]
二、重现后状态：
![image](https://user-images.githubusercontent.com/25498672/94337419-bfb00400-001c-11eb-8931-a51c261df6c0.png)

**Comment by 199621616** [comment]
4、不是有问题，是希望增加功能，扩展可支持序列化为动态对象。它特别灵活，对于开发复杂系统特别有用。目前Blazor Server 就可以支持它，但是Blazor WebAssembly目前不支持。Blazor Server示例代码：


@page "/fetchdata"

@using AdmBlazor.Data
@inject DatabaseService ForecastService

<h1>Weather forecast</h1>

<p>This component demonstrates fetching data from a service.</p>

@if (forecasts == null)
{
    <p><em>Loading...</em></p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Temp. (C)</th>
                <th>Temp. (F)</th>
                <th>Summary</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var forecast in forecasts)
            {
                <tr>
                    <td>@forecast.Id</td>
                    <td>@forecast.登录名</td>
                    <td>@forecast.别名</td>
                    <td>@forecast.邮箱</td>
                </tr>
            }
        </tbody>
    </table>
}

@code {
    private IEnumerable<dynamic> forecasts;

    protected override async Task OnInitializedAsync()
    {
        forecasts = await ForecastService.GetAspNet04Async("");
    }
}

**Comment by 199621616** [comment]
WinForm is not supported at this time, we can use WPF instead. Everything else is fine, and what we need now is a third-party component that can work properly with blazor. It's not clear if other third-party components are available https://github.com/stsrki/Blazorise Does not appear to work on 0.4.

**Comment by Eilon** [comment]
This is now done as part of #317, fixed by PR #318 !
