### ISSUE TITLE
Problems with images

### ISSUE THREAD

**Issue by valweicht** [xamarin/MobileBlazorBindings#185]
The following: 
"img src="/images/XXX YYY.jpg" doesn't work. 
Renaming image to XXXYYY.jpg and using  "img src="/images/XXXYYY.jpg" works.
Also problem with:
"use xlink:href="/images/icons.svg#myicon"

**Comment by Eilon** [comment]
Hi @valweicht I'm sorry you're having this problem.

Can you share more info about what you tried and what doesn't work? These look like HTML tags so can you share details about where you placed the tags? If you can post your project in a GitHub repo that would also help.

**Comment by valweicht** [comment]
Hi,  I took your sample apps followed  the setup and it worked fine. I took two jpegs put them into wwwroot/images. One filename has a space in it the other doesn't. I added img tags for the 2 files in index.razor, only the one named without spaces displays.

**Comment by Eilon** [comment]
Got it, I think I can reproduce this now. It seems that the spaces are getting URL-encoded as `%20` and so the file provider can't find the file. Hopefully an easy fix!

**Comment by valweicht** [comment]
There's probably other characters that can happen to. Suspect the same thing with the # when using svg and xlink  xlink:href="/images/icons.svg#icon-menu" > When are you planning on updating the nuget paxkage?

**Comment by Eilon** [comment]
The fix I'm making is to URL-decode the entire path before trying to load the static resource, so any character that might get encoded should also get un-encoded.

For the `xlink:href` issue I've never used that so I'm not sure how to test it. As long as the browser window (a "WebView") gets a URL-looking thing, I'd imagine it would work with my fix. Browsers don't send the `#icon-menu` part of the URL to the server so I don't think that should be an issue.

Once my fix is checked in, the packages will be updated automatically on the nightly feed, which you can read about here: https://docs.microsoft.com/mobile-blazor-bindings/contribute/nightly-builds

And then we'll have an official preview release once a few more changes are in.

**Comment by valweicht** [comment]
Got it - thanks! By the way problem also seems to occur in CSS when using spaces in file name for background images, Hopefully your fix will take care of that too.

**Comment by Eilon** [comment]
It seems that CSS works just fine now too.

I have this CSS:

```css
html, body {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    background-image: url('/images/another test image.png')
}
```

And I get this "beautiful" UI rendered:

![image](https://user-images.githubusercontent.com/202643/94321762-69bc5d00-ff45-11ea-99b4-d1cd25f92105.png)

**Comment by Eilon** [comment]
If you want to try out the fix, follow the instructions for nightly builds and the new package should be there: https://docs.microsoft.com/mobile-blazor-bindings/contribute/nightly-builds

**Comment by valweicht** [comment]
Already have it thankyou again,

**Comment by Eilon** [comment]
Wonderful, thank you for reporting this issue to help make Mobile Blazor Bindings even better!

**Comment by valweicht** [comment]
Hi I see you closed yjis but there is still a small problem with svgs
&llt;svg width="30" height="30" &gt;
    &llt;use xlink:href="/images/icons.svg#icon-home"&gt;&llt;/use&gt;
&llt;/svg&gt;

**Comment by valweicht** [comment]
The following still, doesn't work. I ran the repo, but the URL doesn't come through GetResourceFilenameFromUrl. I'm guessing your parsing the html but not picking up svg/use element.
```html
<svg width="30" height="30">
    <use xlink:href="/images/icons.svg#icon-home"></use>
</svg>
```

**Comment by Eilon** [comment]
All the HTML is processed by the native web view components on each platform. Blazor doesn't parse any HTML in this scenario. Which platform are you running?

Also, I'm not familiar with exactly how to use SVG - is the SVG snippet you showed a complete snippet that I can use within an HTML file, or is anything else required?
