### ISSUE TITLE
How to make Navigation and Authorization Screen ?

### ISSUE THREAD

**Issue by outdomleap** [xamarin/MobileBlazorBindings#188]

**Comment by ktaze1** [comment]
I don't know what you exactly meant with Navigation but for Authenticating and authorizing you need a server.


I've try such a thing and added a Web Application project [in my repo](https://github.com/ktaze1/CugemderMobileApp), and added custom `AuthenticationStateProvider` to shared client project. Also to handle http request I've added AppState class and Data Access Layer classes for accessing the APIs. By running server and android project I can login with authentication. `AuthorizeView` works normally. However if you want to use Roles, you also need to include it to your JWT claims. I couldn't handle it yet. Also beware my solution guaranteed not the best solution, actually it might even be bad one. So proceed with caution.

**Comment by outdomleap** [comment]
I want to create screen navigation or page navigation on Blazor Mobile Binding, How can i do? I'm not see this component on document.

**Comment by Eilon** [comment]
The recommended pattern for navigation is to use the Shell component. The ControlGallery sample in this repo shows how to use Shell along with the navigation feature to navigate to different pages.

The main project is here: https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/ControlGallery/ControlGallery

And this file shows how to perform navigation: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/ControlGallery/ControlGallery/Views/PlaygroundList.razor

And this file shows how to declare the page navigation path of a page: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/ControlGallery/ControlGallery/Views/CommonControls.razor#L1

And Shell automatically provides the "Back" button. With Shell you can also have a "flyout menu", or have it disabled, as in this sample. You can learn more about the Xamarin.Forms Shell features here: https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell/. Please note that not all Xamarin.Forms Shell features are supported yet in Mobile Blazor Bindings at this time
