### ISSUE TITLE
[Bug] Navigation Manager's Force Reload gives error.

### ISSUE THREAD

**Issue by ktaze1** [xamarin/MobileBlazorBindings#190]
Injecting `NavigationManager` and routing works on WebUI but forcing page to reload with `navigationManager.NavigateTo("url", true)` breaks the app, giving 
``` 
System.ArgumentNullException
Message=Value cannot be null.
Parameter name: stream
```
and ending the debugging session.

I used force reload for refreshing the page after a database operation but I was able to reproduce it with a new project. 

In Index razor:
Trying to refresh page with Navigation Manager with` <button @onclick="@( () => uriHelper.NavigateTo("", true))"> Reload page </button> `  gives blank page while,

navigating to another page with `forceReload` = true  (` <button @onclick="@( () => uriHelper.NavigateTo("/counter", true))"> Reload page </button> ` ) This gives the ArgumentNullException

Debug Output:
```
10-01 14:03:04.290 E/mono    (10320): 
10-01 14:03:04.290 E/mono    (10320): Unhandled Exception:
10-01 14:03:04.290 E/mono    (10320): System.ArgumentNullException: Value cannot be null.
10-01 14:03:04.290 E/mono    (10320): Parameter name: stream
10-01 14:03:04.290 E/mono    (10320):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.42(intptr,intptr,intptr,intptr)
10-01 14:03:04.290 E/mono    (10320):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.42(intptr,intptr,intptr,intptr)
10-01 14:03:04.291 E/mono-rt (10320): [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null.
10-01 14:03:04.291 E/mono-rt (10320): Parameter name: stream
10-01 14:03:04.291 E/mono-rt (10320):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.42(intptr,intptr,intptr,intptr)
10-01 14:03:04.291 E/mono-rt (10320):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.42(intptr,intptr,intptr,intptr)
```

This happened on Android (with both API 28 & 30). Let me know if there are more information you need.

**Comment by Eilon** [comment]
Hi @ktaze1 thanks for reporting this issue. I haven't seen this before so I'll make sure we investigate this and see how to fix it.

**Comment by ktaze1** [comment]
Hey @Eilon, do you happen to have any update on this issue?

**Comment by Eilon** [comment]
Not yet, but it's on the list.
