### ISSUE TITLE
It is suggested to add automatic update mechanism as soon as possible

### ISSUE THREAD

**Issue by 199621616** [xamarin/MobileBlazorBindings#194]
In modern applications, there is an urgent need for fast iterative updating. Electron has many success factors, and automatic update is an important part of it. Any user developing hybrid applications needs this important feature. I think the hybrid application of mobile blazor binding has the opportunity to surpass electronic, but it still lacks the very important link of automatic update. Let users put their energy into the implementation of business logic instead of doing a half baked project.

**Comment by Eilon** [comment]
This suggestion is tracked here: https://github.com/xamarin/MobileBlazorBindings/issues/23

Please vote on that issue or add any comments to it so that we can consolidate this request. Thank you!
