### ISSUE TITLE
Provide a way to debug BlazorWebView

### ISSUE THREAD

**Issue by Kukks** [xamarin/MobileBlazorBindings#197]
A way to expose the console output of the webview or even better, a way to remotely connect via devtools is needed. 
I have an issue after adding some test code in the default demo and the IDE doesn't seem to spit out anything regarding the error, there is no web mode to test in a browser, and the app does not render an error on screen, just the router redirects back to previous page.

**Comment by Eilon** [comment]
Hi @Kukks it's definitely possible to debug the web portion of a hybrid app. We have some initial docs here: https://docs.microsoft.com/mobile-blazor-bindings/advanced/debug-hybrid-apps

Some parts of the doc are still missing, but in general you use the regular browser dev tools either locally (such as on macOS or Windows), or if the code is running in an emulator, you can still use the desktop browser's dev tools to debug it!
