### ISSUE TITLE
Support for using css from another class library in hybrid apps.

### ISSUE THREAD

**Issue by musictopia2** [xamarin/MobileBlazorBindings#198]
I have been unable to use css from an external library.  For example, if I add a new razor class library to the solution to the template and use that component, all the css was gone.  Tried to use this code in the index.html
<link href="_content/SampleLibrary/styles.css" rel="stylesheet" />

and even added this code in the app.cs
var tt = typeof(Component1);
            BlazorHybridHost.AddResourceAssembly(tt.Assembly, contentRoot: "wwwroot");

but still would not show the css from external files.  It would be a huge disappointment if all css has to be in one library.  It would mean if using any third party component that had css or javascript, they would not work properly.

**Comment by Eilon** [comment]
Indeed, that is a feature we are working on here: https://github.com/xamarin/MobileBlazorBindings/issues/129

And this is planned for the upcoming Preview 5, so we should have it working soon!
