### ISSUE TITLE
[Help Wanted] Running the Samples locally

### ISSUE THREAD

**Issue by DevCisse** [xamarin/MobileBlazorBindings#205]
I am trying to the samples locally. I don't know If I am doing it correctly though. For instance, the Todo sample on visual studio I selected 'scope to this ' and try to run I get this error.

![image](https://user-images.githubusercontent.com/45653783/97480036-2e052080-1953-11eb-866f-e630b0d0fb1d.png)

**Comment by Eilon** [comment]
Hmm I haven't seen this before. It's complaining about MAX_PATH, which is a Windows limit of 260 chars. Can you try moving the whole solution to a shorter path? So instead of `E:\MobileBlazorbindings-master\MobileBlazorbindings-master\...` maybe `E:\MBB\..`? At least just to see if that's the only problem.

**Comment by DevCisse** [comment]
Okay. I will try that.

**Comment by DevCisse** [comment]
> Hmm I haven't seen this before. It's complaining about MAX_PATH, which is a Windows limit of 260 chars. Can you try moving the whole solution to a shorter path? So instead of `E:\MobileBlazorbindings-master\MobileBlazorbindings-master\...` maybe `E:\MBB\..`? At least just to see if that's the only problem.


That was the only problem. Its working now. Thanks

**Comment by Eilon** [comment]
Glad you got it working! I'm not sure why the Android stuff failed with MAX_PATH because these days I think most apps aren't restricted by it, but certainly some still are.

I'm leaving this bug open so I can see if I can get to the bottom of this.

**Comment by jspuij** [comment]
Hahaha anyone ever trying to develop java code knows this issue. I have a c:\o\ directory for the openHAB source code for especially this reason. The endless nesting of namespaces and full class names typically trigger this.

**Comment by DevCisse** [comment]
> Glad you got it working! I'm not sure why the Android stuff failed with MAX_PATH because these days I think most apps aren't restricted by it, but certainly some still are.
> 
> I'm leaving this bug open so I can see if I can get to the bottom of this.

Will love to participate

**Comment by Eilon** [comment]
It looks like this is a common enough problem that there is a doc on how to work around the issue: https://docs.microsoft.com/xamarin/android/troubleshooting/questions/path-too-long-exception

I'm closing this issue here because it is external to the project.
