### ISSUE TITLE
Issues found while implementing Authentication

### ISSUE THREAD

**Issue by jspuij** [xamarin/MobileBlazorBindings#212]
As said I'm implementing authentication atm. This issue will serve as my memory as I encounter issues.

**Comment by jspuij** [comment]
WebAssembly Auth adds the default options as singletons. However one of these (the first) takes a dependency on NavigationManager, which is scoped. This is ok for webassembly as there is no scope created. We do create scopes in MBB however, which leads to an exception. At least the first one should be scoped. We will fix this, however we should report this back to the aspnetcore team.

https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly.Authentication/src/WebAssemblyAuthenticationServiceCollectionExtensions.cs#L118
https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly.Authentication/src/WebAssemblyAuthenticationServiceCollectionExtensions.cs#L206

As a result RemoteAuthenticationManager should take an IOptionsSnapshot instad of IOptions:

https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs#L64

**Comment by jspuij** [comment]
And found another one on logout. This should take IOptionsSnapshot as well:

https://github.com/dotnet/aspnetcore/blob/648c15dbe90fb8c113f7c6b4adeb40d9e10494f6/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/DefaultRemoteApplicationPathsProvider.cs#L13

**Comment by jspuij** [comment]
Redirects to a custom app scheme on iOS do not work. We will have to intercept the redirect ourselves and notify Blazor somehow.

**Comment by jspuij** [comment]
Finally the nail in the coffin for this route: the javascript oidc client does an authenticaion check inside an iframe all in javascript. This is why we are losing the authentication state and this is why the android and iOS browsers experience delays. There is no way to feed that redirect back to the browser. It's an XHR request. Capturing it and handling it from .NET is not possible. Interopping it to javascript feels very brittle. Also it's against good security practice to NOT show the URL bar during redirect to external providers. The way we have implemented it now there is no guard against MTM as users cannot see the URL.

**Comment by TrieBr** [comment]
> does an authenticaion check inside an iframe all in javascript. This is why we are losing the authentication state and this is why the android and iOS browsers experience delays

Would redirecting (instead of an iframe) help with the issue? This is also a problem on Web clients for certain identify providers which block iframes via `X-Frame-Options deny` (see: https://github.comdotnet/aspnetcore/issues/22343#issuecomment-708477026). Seems like another case for the interop to support an option to use `signinRedirect` instead of `signinSilent` in https://github.com/IdentityModel/oidc-client-js. Although that's just one piece of the puzzle

**Comment by jspuij** [comment]
@TrieBr Thank you for your comment. It would be an option to just remove silent authentication altogether, but this would mean (especially on reload, which might happen during memory pressure when your app is restarted, or during navigation to an external page outside the app scheme and back, that blazor would restart and you would auto redirect to the login provider. Or we just don't check the authentication state at all anymore but that would log you out. There are some other options though, (most notably implementing our own IframeNavigator that would just interop everything to .NET).

Question is whether it is worth it or going with the .NET oidc library and using the system browser is a better alternative.

Your link is missing a slash BTW, the correct one (for reference) is: https://github.com/dotnet/aspnetcore/issues/22343#issuecomment-708477026

**Comment by jspuij** [comment]
@ktaze1 This is because it cannot check the authentication state online as the request is blocked. See https://github.com/xamarin/MobileBlazorBindings/issues/212#issuecomment-722936711

ATM I'm moving away from using an embedded webview for authentication, using OS primitives instead on the mobile platforms. This authentication will use the .NET oidc client instead of the javascript one. Expect this to land in the nightly builds in one or two weeks.

**Comment by jspuij** [comment]
The callback Url schemes are not unique on android, so you get a popup requesting which application to redirect to in case you have two applications installed with the same scheme.

**Comment by jspuij** [comment]
Logout does not work on Native MBB application.

**Comment by Eilon** [comment]
@jspuij - just checking, is it correct to have this bug closed via your PR? Or is anything from this issue still remaining?
