### ISSUE TITLE
Can third party JS UI controls be used with MBB?

### ISSUE THREAD

**Issue by thenrich2009** [xamarin/MobileBlazorBindings#214]
Can UI Control libraries like Telerik Kendo UI and DevExpress DevExtreme be used with MBB? This requires JS interop that Blazor uses to call JS functions.

Or jQuery and any jQuery plugin?

**Comment by jspuij** [comment]
Yes, this works without issue.

**Comment by Eilon** [comment]
Indeed, `JSInterop` is supported in Mobile Blazor Bindings as of Preview 5, which was released a few days ago. If you have any issues with a 3rd party control please let us know by filing an issue with all the details.
