### ISSUE TITLE
Using AuthorizeView with Shell

### ISSUE THREAD

**Issue by Dreamescaper** [xamarin/MobileBlazorBindings#217]
I'm trying to use asp net core auth with Mobile Blazor (by registering custom `AuthenticationStateProvider` and storing jwt token in SecureStorage) and use AuthorizedView component. So I want to show login page when user is not authenticated, so I'm trying to do something like that:
```razor
<CascadingAuthenticationState>
    <Shell>
        <AuthorizeView>
            <Authorized>
                <TabBar>
					<Tab Icon="Icons.Home">
					    <HomePage />
					</Tab>
					<Tab Icon="Icons.Person">
					    <ProfilePage />
					</Tab>
                </TabBar>
            </Authorized>
            <NotAuthorized>
                <TabBar>
                    <Mobile.Pages.LoginPage />
                </TabBar>
            </NotAuthorized>
        </AuthorizeView>
    </Shell>
</CascadingAuthenticationState>

```

And it basically works - with the exception of refreshing when state changes. So if I log in or log out, I have to reopen the app to see updated results.
I've tried injecting `AuthenticationStateProvider`, and invoke `StateHasChanged` explicitly on `AuthenticationStateChanged` event, but that has no effect.

I've also tried to put AuthorizedView inside TabBar:
```razor
                <TabBar>
			        <AuthorizeView>
			            <Authorized>
							<Tab Icon="Icons.Home">
							    <HomePage />
							</Tab>
							<Tab Icon="Icons.Person">
							    <ProfilePage />
							</Tab>
			            </Authorized>
			            <NotAuthorized>
			                <Tab>
			                    <Mobile.Pages.LoginPage />
			                </Tab>
			            </NotAuthorized>
		        	</AuthorizeView>
               	</TabBar>
```
This way I can see at least some updates - new tabs are added, but never removed from Shell (so I see login page as separate tab after logout).

Is there anything I do wrong here?
Thanks!

**Comment by Eilon** [comment]
Oh this is cool! (Even though it isn't working 😄 )

I'm guessing this involves some UI update scenarios that might not be fully implemented yet. I am now vaguely recalling that maybe the Shell wrapper doesn't support removing tabs (the real Shell in Xamarin.Forms should).

I'll take a look, hopefully an easy fix!

**Comment by Dreamescaper** [comment]
@Eilon 
I assume that's because ElementManager.RemoveElement only supports Views, right?
https://github.com/xamarin/MobileBlazorBindings/blob/3a970afde40ac8107264bcaac962a6e2cfa015da/src/Microsoft.MobileBlazorBindings/MobileBlazorBindingsElementManager.cs#L63-L74

WDYT about adding method `RemoveChild` to `IXamarinFormsElementHandler` to be able to handle various parents?

**Comment by Eilon** [comment]
Yup, the fix is definitely something along those lines, thanks for digging in! If you'd like, feel free to take a crack at a PR. I'm not sure how involved the change is, but it probably involves changing any file that is a container type (as you seem to have discovered).

**Comment by Dreamescaper** [comment]
@Eilon 
Yep, I can work on that a bit later.

I have only one question so far. Is there any easy way to get parent ElementHandler from child ElementHandler?

Otherwise I'd probably replace `ElementManager.RemoveElement(IElementHandler handler)` method with `ElementManager.RemoveChild(IElementHandler parent, IElementHandler child)` method, if that acceptable change.

**Comment by Eilon** [comment]
Hmm I'd have to dig into the code to see for sure.

I think doing your suggestion here would be fine:

> WDYT about adding method `RemoveChild` to `IXamarinFormsElementHandler` to be able to handle various parents (probably with empty implementation in `ElementHandler`)?

And in places where it doesn't make sense, it throws NotSupportedException like this:

https://github.com/xamarin/MobileBlazorBindings/blob/master/src/Microsoft.MobileBlazorBindings/Elements/Handlers/GestureRecognizerHandler.cs#L43-L47

**Comment by Eilon** [comment]
(I think much of this API needs some major refactoring in the future, but for now I think a tactical change might be the best course.)

**Comment by Eilon** [comment]
BTW I doubt this is a regression because this scenario was never well tested before. I think this PR is a huge step forwards in the design and implementation so depending on how things go, we could take this PR after I do a bit more testing, and leave the rest for a follow-up investigation.

**Comment by Eilon** [comment]
I pushed a change that adds a Remove button as well. Weirdly, you can remove & add tabs, but you can only _remove_ shell contents! Adding shell contents is not allowed.

**Comment by Eilon** [comment]
Thank you so much @Dreamescaper for taking the initiative on this change and coming up with a terrific solution!
