### ISSUE TITLE
How to display images in hybrid web view

### ISSUE THREAD

**Issue by AmirImam** [xamarin/MobileBlazorBindings#221]
Hi
I want to display image in razor page in web view. I tried to set the image in wwwroot folder in class library project, then in wwwroot in android project, and finally in resources in android, but always the image not displayed (not found)
I want to know where I have to set the images, and how to display it and use it as css background-image

**Edit:**
I tried to wirite the src like that "_content/{{projectName}}/myImage.png" and it worked
Tested it on android 9

**Comment by Eilon** [comment]
Indeed, the image would typically be in the shared project that has the Razor files in the `wwwroot` folder (or a sub-folder of it), and then you reference it like `_content/PROJECT_NAME/image.png`.
