### ISSUE TITLE
Refreshing WebView does not re-render

### ISSUE THREAD

**Issue by jburman** [xamarin/MobileBlazorBindings#234]
On Windows 10 using unmodified Hybrid template.  Right clicking in the web view and selecting Refresh or hitting F5 causes the web view to go blank.  Looking in the DOM the <app> element is empty.  I don't see any obvious errors occurring though.

**Comment by Eilon** [comment]
Oh boy, this is probably fixed as of just a day or two ago thanks to @jspuij 's work!

You can try using the nightly feed per the info here: https://docs.microsoft.com/mobile-blazor-bindings/contribute/nightly-builds

And that will get you updated NuGet packages that most likely fix this very issue.

Would you mind trying that out and letting us know if it fixes your issue?

**Comment by jburman** [comment]
Ok, updated to 0.6.6-preview and it does appear to be fixed.  Thanks for the update!

**Comment by Eilon** [comment]
That's great to hear, thank you for trying it out!

**Comment by Akdimi** [comment]
Hi, this fixed the refreshing thing. But when you navigate to third party website and then redirect back to the app the page is blank. When looking at the elements in html everything is there except there is nothing inside the <app> tag. Is there a way to handle this correctly? I tried almost everything  like mapfallback to file is server startup etc.. i can redirect to the page but the app is not loaded in the app tag and there are no errors.

**Comment by Eilon** [comment]
@Akdimi can you log a new issue for this?

**Comment by Akdimi** [comment]
> @Akdimi can you log a new issue for this?

I did two days ago. Here is the link https://github.com/dotnet/MobileBlazorBindings/issues/372#issue-910980263
