### ISSUE TITLE
How can to hide shell header navigator?

### ISSUE THREAD

**Issue by outdomleap** [xamarin/MobileBlazorBindings#248]
![image](https://user-images.githubusercontent.com/65535691/100172497-0aee7200-2efb-11eb-8345-ad2b30404f61.png)

**Comment by jspuij** [comment]
You should be able to use  `Shell.SetNavBarIsVisible(<contentpage>, false)` on the (probably) contentPage that is loaded; You might need to create a [reference ](https://docs.microsoft.com/en-us/mobile-blazor-bindings/advanced/access-native-controls#accessing-native-xamarinforms-controls-from-blazor-components )to the native control to be able to access the content page from the `@code{}` section.

**Comment by Dreamescaper** [comment]
You can take a look at example here: https://github.com/xamarin/MobileBlazorBindings/issues/11#issuecomment-720249046

(You need `SetNavBarIsVisible` instead of `SetTabBarIsVisible`)

**Comment by outdomleap** [comment]
when i follow that step it show error like this

![image](https://user-images.githubusercontent.com/65535691/100298467-cbd82380-2fc3-11eb-8419-a4befac129b8.png)

**Comment by Dreamescaper** [comment]
Could you share your razor file?
Note that you you need to access NativeElement after first render, otherwise it's not created yet.

**Comment by outdomleap** [comment]
Okay now it working

Thank you!

**Comment by Eilon** [comment]
Glad you got it working! And thanks @Dreamescaper for assisting!
