### ISSUE TITLE
Working with a prepopulated SQLite database

### ISSUE THREAD

**Issue by DevCisse** [xamarin/MobileBlazorBindings#256]
How do I grab data from tables of a prepopulated SQLite database?

**Comment by Eilon** [comment]
Hi @DevCisse I'm not sure I fully understand the question. Is there anything special about a pre-populated SQLite database? If it's the same as any other SQLite database then all the regular SQLite APIs should work.

There's a Todo App sample that uses SQLite: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoItemDatabase.cs

**Comment by DevCisse** [comment]
Yes, where would the database file be placed? Assests folder or shared project?

That aside, this https://youtu.be/aQtNynTLhl4 video helped me with the task. 
```

 Assembly assembly = IntrospectionExtensions.GetTypeInfo(typeof(App)).Assembly;

            Stream embeddedDatabaseStream = assembly.GetManifestResourceStream("MobileBlazorBindingsTodo.TodoSQLite.db3");

            if (File.Exists(dbPath))
            {
                FileStream fileStreamToWrite = File.Create(dbPath);
                embeddedDatabaseStream.Seek(0, SeekOrigin.Begin);
                embeddedDatabaseStream.CopyTo(fileStreamToWrite);
                fileStreamToWrite.Close();
            }


            _database = new SQLiteAsyncConnection(dbPath);
            _database.CreateTableAsync<TodoItem>().Wait();
            _dbChanged = dbChanged ?? throw new ArgumentNullException(nameof(dbChanged));

```

**Comment by Eilon** [comment]
It looks like that video has the answers? The answer for Xamarin in the video should be the same for Mobile Blazor Bindings. Were you able to get it working from the video?

**Comment by DevCisse** [comment]
Yes it has the answers and I was able to get it working.

**Comment by Eilon** [comment]
Great!
