### ISSUE TITLE
MBB templates missing on Nuget?

### ISSUE THREAD

**Issue by dcuccia** [xamarin/MobileBlazorBindings#262]
At the moment, I'm having trouble pulling the MobileBlazorBindings templates with the command:

`dotnet new -i Microsoft.MobileBlazorBindings.Templates::0.5.50-preview`

The error returned for me is:

> Determining projects to restore...
> C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp1.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\dcucc.templateengine\dotnetcli\v5.0.100\scratch\restore.csproj]
> Restored C:\Users\dcucc.templateengine\dotnetcli\v5.0.100\scratch\restore.csproj (in 1.33 sec).

Investigating further, I checked for any newer versions here:

https://www.nuget.org/packages/Microsoft.MobileBlazorBindings.Templates

...and saw nothing new there. For fun, I checked Fuget:

https://www.fuget.org/packages/Microsoft.MobileBlazorBindings.Templates

...and received an "Error Reading Package" notice:

> System.IO.InvalidDataException: End of Central Directory record could not be found.
> at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
> at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
> at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
> at FuGetGallery.PackageData.Read(MemoryStream bytes, HttpClient httpClient) in D:\home\site\repository\Data\PackageData.cs:line 118
> at FuGetGallery.PackageData.PackageDataCache.<>c__DisplayClass2_0.b__0() in D:\home\site\repository\Data\PackageData.cs:line 412
> at System.Threading.Tasks.Task.InnerInvoke()
> at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
> --- End of stack trace from previous location where exception was thrown ---
> at FuGetGallery.PackageData.PackageDataCache.ReadPackageFromUrl(PackageData package, HttpClient httpClient, CancellationToken token) in D:\home\site\repository\Data\PackageData.cs:line 412
> at FuGetGallery.PackageData.PackageDataCache.GetValueAsync(String arg0, PackageVersion arg1, HttpClient httpClient, CancellationToken token) in D:\home\site\repository\Data\PackageData.cs:line 385

So, it seems like the package is cached on Nuget's site, but actually missing.

**Comment by jspuij** [comment]
@dcuccia That is a warning, not an error. It does not affect the installation of the templates. The package is on nuget. If you specify a version on fuget, you will actually get the correct data: https://www.fuget.org/packages/microsoft.mobileblazorbindings.templates/0.5.50-preview

**Comment by Eilon** [comment]
Indeed, the template packages are all on NuGet here: https://www.nuget.org/packages/Microsoft.MobileBlazorBindings.Templates
And 0.5.50-preview is right now the latest package.

The issue on FuGet seems to be a bug in FuGet and I will see if I can submit a fix to them for that.

As far as the `netcoreapp1.0` warning (which, to be clear, is really just a warning), it seems like it's a bug that got fixed: https://github.com/dotnet/templating/issues/2627

**Comment by dcuccia** [comment]
Thanks both. 

@jspuij I made the mistake of assuming the error I was seeing was the same on both of my machines, sorry. You're right that it's a warning. The true error on the first machine is included here:

> PS C:\Projects\temp> dotnet new -i Microsoft.MobileBlazorBindings.Templates::0.5.50-preview
>   Determining projects to restore...
> C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp1.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\David\.templateengine\dotnetcli\v5.0.100\scratch\restore.csproj]
>   Failed to download package 'Microsoft.MobileBlazorBindings.Templates.0.5.50-preview' from 'https://www.nuget.org/api/v2/package/Microsoft.MobileBlazorBindings.Templates/0.5.50-preview'.
>   The SSL connection could not be established, see inner exception.
>      Received an unexpected EOF or 0 bytes from the transport stream.
>   Failed to download package 'Microsoft.MobileBlazorBindings.Templates.0.5.50-preview' from 'https://www.nuget.org/api/v2/package/Microsoft.MobileBlazorBindings.Templates/0.5.50-preview'.
>   The SSL connection could not be established, see inner exception.
>      Received an unexpected EOF or 0 bytes from the transport stream.
> C:\Program Files\dotnet\sdk\5.0.100\NuGet.targets(131,5): error : Failed to download package 'Microsoft.MobileBlazorBindings.Templates.0.5.50-preview' from 'https://www.nuget.org/api/v2/package/Microsoft.MobileBlazorBindings.Templates/0.5.50-preview'. [C:\Users\David\.templateengine\dotnetcli\v5.0.100\scratch\restore.csproj]
> C:\Program Files\dotnet\sdk\5.0.100\NuGet.targets(131,5): error : The SSL connection could not be established, see inner exception. [C:\Users\David\.templateengine\dotnetcli\v5.0.100\scratch\restore.csproj]
> C:\Program Files\dotnet\sdk\5.0.100\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\Users\David\.templateengine\dotnetcli\v5.0.100\scratch\restore.csproj]
> C:\Program Files\dotnet\sdk\5.0.100\NuGet.targets(131,5): error : The feed 'nuget.org [https://www.nuget.org/api/v2/]' lists package 'Microsoft.MobileBlazorBindings.Templates.0.5.50-preview' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. [C:\Users\David\.templateengine\dotnetcli\v5.0.100\scratch\restore.csproj]
> C:\Program Files\dotnet\sdk\5.0.100\NuGet.targets(131,5): error :   Unable to find package 'Microsoft.MobileBlazorBindings.Templates.0.5.50-preview'. [C:\Users\David\.templateengine\dotnetcli\v5.0.100\scratch\restore.csproj]

Looks like an SSL issue isolated to one machine. I will look into this further.

@Eilon I did submit a ticket here: https://github.com/praeclarum/FuGetGallery/issues/123
...and it looks like they're tracking that already.

**Comment by Eilon** [comment]
Well this is just one of those fun issues where 3 or 4 unrelated issues all come up and cause a huge headache 😄

**Comment by jspuij** [comment]
> Looks like an SSL issue isolated to one machine. I will look into this further.

@dcuccia Is this the machine where you opened that email from the late Mrs Sanders that promises you $7.000.000 as her beneficiary. 😁😉

**Comment by dcuccia** [comment]
@jspuij but...I told her I wasn't interested!
