### ISSUE TITLE
Fix Android extraction logic to fully overwrite existing file

### ISSUE THREAD

**Issue by Eilon** [xamarin/MobileBlazorBindings#264]
The Android Asset File Provider needs to extract all the files in the ZIP so that they can be used. It correctly overwrites any existing files (if the CRC32 doesn't match), but it doesn't _reset_ the file size. So if you overwrite a "large" file with a "small" file then the extra content from the end of the "large" file will continue to exist.

The fix is to reset the file back to length 0 so that when the new smaller content is written there won't be any extra junk at the end.

**Comment by jspuij** [comment]
Oops

**Comment by Eilon** [comment]
I kept wondering how did all this extra HTML get into my page and it's invalid?!? Oops! 😁

**Comment by jspuij** [comment]
I only ever create a bigger mess, so I never noticed 😂

**Comment by Eilon** [comment]
Haha yeah I'm not really sure _why_ I had the problem. It was in index.html and I guess I had an extra CSS tag at one point and removed it, so the new index.html was smaller. I had to scratch my head a whole lot on this one!
