### ISSUE TITLE
Assigning delegate object to the UNUserNotificationCenter object on iOS Hybrid 

### ISSUE THREAD

**Issue by ktaze1** [xamarin/MobileBlazorBindings#267]
Hello.

I hope this is not iOS version of #191 I hope there is no harm to ask :)

I was following [this tutorial](https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/docs/Firebase/CloudMessaging/GettingStarted.md#setting-up-a-firebase-cloud-messaging-client-app-on-ios) to implement notifications through FCM. At their [Register for remote notifications](https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/docs/Firebase/CloudMessaging/GettingStarted.md#register-for-remote-notifications) section there is a code snippet:

Project.iOS/AppDelegate.cs:
```
// Register your app for remote notifications.
if (UIDevice.CurrentDevice.CheckSystemVersion (10, 0)) {
	
	// For iOS 10 display notification (sent via APNS)
	UNUserNotificationCenter.Current.Delegate = this;

	var authOptions = UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Sound;
	UNUserNotificationCenter.Current.RequestAuthorization (authOptions, (granted, error) => {
		Console.WriteLine (granted);
	});
} else {
	// iOS 9 or before
	var allNotificationTypes = UIUserNotificationType.Alert | UIUserNotificationType.Badge | UIUserNotificationType.Sound;
	var settings = UIUserNotificationSettings.GetSettingsForTypes (allNotificationTypes, null);
	UIApplication.SharedApplication.RegisterUserNotificationSettings (settings);
}

UIApplication.SharedApplication.RegisterForRemoteNotifications ();
```

So seems like there are no problem but when I implemented this to my MBB hybrid project the line:
`UNUserNotificationCenter.Current.Delegate = this;`
gives an error, saying `Cannot implicitly convert type 'MyApp.iOS.AppDelegate' to UserNotifications.IUNUserNotificationsCenterDelegate'. An explicit conversion exists`

It won't let me compile but if I explicitly cast it into what it wants it also gives error. 

Found [another example](https://gist.github.com/codercampos/7084dd0e9d0f47b0a306122f9da248e9#file-firebaseappdelegate-cs) of Xamarin Forms [at this post](https://xamarinlatino.com/xamarin-forms-firebase-cloud-messaging-ios-setup-1961a91d4055) (I translated mostly since I don't know Spanish) and they're doing the same. 

What is the problem here? I couldn't solve it. Thanks in advance.

**Comment by Eilon** [comment]
Well there shouldn't be anything that's Mobile Blazor Bindings specific here because MBB is all about UI controls, and this is about an OS service.

I can try to take a look at this but this question might be better suited to a place like https://github.com/xamarin/xamarin-macios.
