### ISSUE TITLE
Issue starting mac app from default hybrid template (Xamarin.Mac)

### ISSUE THREAD

**Issue by PI2R** [xamarin/MobileBlazorBindings#270]
Hi,

I installed the latest visual studio 2019 pro preview.
I installed Microsoft.MobileBlazorBindings.Templates 0.5.50-preview
I installed all latest preview of the different nuget packages coming with the default hybrid blazor app.
I installed all latest preview version of vs and packages on the mac.

I paired to the mac successfully.

When I start the mac project I get the following exception when executing the line "NSApplication.Init();" of the main.cs:
System.IO.FileNotFoundException: Could not load file or assembly 'Xamarin.Mac, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'  or one of its dependencies.

When I force the "Copy to local" on the Xamarin.Mac reference, I get the an exception raised by AppKit.NSApplication with 2 inner exceptions:

- TypeInitializationException: exception raised by type initializer 'ObjCRuntime.Selector'
- DllNotFoundException: unable to load DLL '/usr/lib/libobjc.dylib' could not find module

FYI:

- I think this is a known issue but I also get a warning at build time for the android and mac projects  saying "Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved.
- Android project works well

Any help is more than welcome. 

Thanks in advance

**Comment by PI2R** [comment]
How do I delete this stupid question? :-)
I am realizing that all this is only to simulate iOS and to test macOS version I need to do so on the mac itself...
I don't even know why I let myself thinking it would be possible... I might be too tired :-)

**Comment by Eilon** [comment]
@PI2R I'm glad you got it working! I disagree that it is a stupid question, I'm quite certain I tried doing the exact same thing before!
