### ISSUE TITLE
Xamarin Forms 5 breaking changes

### ISSUE THREAD

**Issue by lachlanwgordon** [xamarin/MobileBlazorBindings#277]
Xamarin Forms 5 will come out of pre-release any day now and there are some breaking changes. https://github.com/xamarin/Xamarin.Forms/issues/11857

I think the only one that will affect us will be the migration from MasterDetail to FlyoutView.

Is our goal to upgrade to Xamarin Forms 5 shortly after it goes GA? I think it should be.

**Comment by Dreamescaper** [comment]
FYI Xamarin Forms 5 is released.

I can submit PR later, unless you're planning to.

**Comment by Eilon** [comment]
As long as moving to Xamarin.Forms 5 _works_, then I think it would be great! I have no reason to think it wouldn't, but I don't think anyone has tried 😄
