### ISSUE TITLE
Publish nightly packages go GitHub package feed

### ISSUE THREAD

**Issue by Eilon** [xamarin/MobileBlazorBindings#28]

**Comment by Eilon** [comment]
Nightly feed is now up!

* Browse the gallery: https://dotnet.myget.org/gallery/mobileblazorbindings-nightly
* Use this feed URL in your nuget.config file or VS config: `https://dotnet.myget.org/F/mobileblazorbindings-nightly/api/v3/index.json`

**Comment by Eilon** [comment]
OK so this might change just a bit in terms of feed location. I'll wait until that's settled before closing this issue.

**Comment by Eilon** [comment]
New feed located on an Azure DevOps public feed.

Browse the feed here:

And to use it, add a file named `NuGet.config` to the root of your repo with the following contents:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="mobileblazorbindings-nightly" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/mobileblazorbindings-nightly/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by lachlanwgordon** [comment]
I'm getting a 404 when I try to configure this as a nuget source in Visual Studio Mac

![Screen Shot 2020-08-06 at 9 42 41 am](https://user-images.githubusercontent.com/29908924/89474543-4983e380-d7c9-11ea-8063-b58177c24225.png)

![Screen Shot 2020-08-06 at 9 43 26 am](https://user-images.githubusercontent.com/29908924/89474552-4db00100-d7c9-11ea-9c9a-4d98973c60fb.png)

**Comment by lachlanwgordon** [comment]
Never mind, all good now.

I told VS to use the human version for web browsing rather than the index.json link.

**Comment by Eilon** [comment]
Ah yes, VS is not so good at that kind of human interaction 😄

**Comment by Eilon** [comment]
Official docs on nightly builds are live! https://docs.microsoft.com/mobile-blazor-bindings/contribute/nightly-builds
