### ISSUE TITLE
Hybrid iOS app, <script></script> not working in index.html!

### ISSUE THREAD

**Issue by idylmz** [xamarin/MobileBlazorBindings#288]
Hey everyone,

First of all, thank you for that amazing project. I would like to specify an issue, weirdly no one has ever raise that one.

In Hybrid app, I have arranged everything on Android. It works well. All my css, js files are working, I can interact with JS from C# side, or vice versa. 

But when I return to HybridApp.iOS project, everything works fine until I have a <script></script> tag on my index.html file.
To get to app working, I have tried self closing <script /> tags as in here. It did work. But now it does not see my script files.

For demonstrating, I will provide a small example below.

My custom.js file:

```
window.alerts = {
    SwAlert: (text, title, icon) => {
        swal({
            title,
            text,
            icon
        });
    },
    success: (text, title) => {
        swal({
            title: title ? title : 'Success!',
            text,
            icon: 'success'
        });
    },
    error: (text, title) => {
        swal({
            title: title ? title : 'Error!',
            text,
            icon: 'error'
        });
    }
}
```

My index.html body on every project:

><body>
    <app></app>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_content/MyHybridApp.iOS/Style/JS/custom.js"></script>
</body> 

On iOS I am trying below but that's only because the app doesn't start with <script></script>

><body>
    <app></app>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_content/MyHybridApp.iOS/Style/JS/custom.js" />
</body> 

When I try to interact with JS as:
 
`await _js.InvokeVoidAsync("alerts.error", message, title);`

It doesn't have any problem with Android and works as expected. But when I try to trigger it on iOS the output is:

![Simulator Screen Shot - iPhone 12 - 2021-01-09 at 11 13 00](https://user-images.githubusercontent.com/9085421/104086784-d98ff280-526b-11eb-87a0-1e41228ee597.png)

I have no idea what to try next. I have searched google for the problem but no one seems to have that problem.

**Comment by idylmz** [comment]
Ok, regarding to my post:

I thought I was producing a small piece of code in order to specify the issue. But it seems reproducing the code, solve the issue for me. 

The original problem was with the` jquery and popper js` files because, well they are big. 

In order to keep html executing I have added my script files on header and then added `defer` attribute to each of them

So the final look is: 

`    <script src="_content/Route/To/JS/File/jquery.js" defer></script>`

I don't know if this is because of memory management of iOS or sth like this. But now it looks like a problem with iOS.

**Comment by Eilon** [comment]
Very interesting. It looks like you've resolved the issue but this is certainly something I'll look back to if we see more reports of this.

**Comment by idylmz** [comment]
Actually it is weird no one has ever seen that before. Good thing I asked, because I solved it just by asking.

BTW, this is not the final solution, it is just a workaround I think. Because now I cannot get it work on iPad. But no problem with iPhone.

Right now I have started building my second app with Blazor Hybrid. And 3 more projects are incoming. I really want to use this template. If my solution would work on every device, it would be very good. 

Or maybe I just have to stop using themes which are dependent on jQuery.

**Comment by Eilon** [comment]
jQuery has been around for a long, long time, and will probably continue to be around for a while longer. So it's interesting that there was an issue with it. But, of course, probably not a lot of people have tried using jQuery in this very modern scenario just yet!
