### ISSUE TITLE
[Android] Seeing a blank screen, no content

### ISSUE THREAD

**Issue by davidortinau** [xamarin/MobileBlazorBindings#31]
I created a new project to implement some existing layouts I have, but the page only shows blank. Not sure it's loading at all. Solution attached.

[Archive.zip](https://github.com/xamarin/MobileBlazorBindings/files/4048797/Archive.zip)

<img width="1662" alt="Screenshot 2020-01-10 19 09 04" src="https://user-images.githubusercontent.com/41873/72196281-af97bc00-33dc-11ea-8463-03e78d4f116d.png">

**Comment by filipoff2** [comment]
Same on  MobileBlazorBindingsTodo.Android  
but I changed to 
{
  "sdk": {
    "version": **"3.1.101"**
  }
}
global.json 
-------
Hello, Word ! increment =  **works fine**

**Comment by Eilon** [comment]
BTW to see if there's an exception, make sure to run with the debugger and catch _all_ CLR (.NET) exceptions:

![image](https://user-images.githubusercontent.com/202643/72850245-8a694000-3c5d-11ea-8239-d5e8ad2ac716.png)

**Comment by Eilon** [comment]
I added support for `Entry.IsPassword`, as well as several other missing properties. So, in the next update, this specific scenario should just work.

**Comment by Eilon** [comment]
OK I can't seem to reproduce the blank screen thing. If I have "invalid markup" (such as setting a property that doesn't exist), I see a full-screen stack trace within the app.

So, closing this bug for now. Thanks for the report!
