### ISSUE TITLE
Is <iframe> supported?

### ISSUE THREAD

**Issue by jameslin0312** [xamarin/MobileBlazorBindings#310]
I am traying add ifame element with src defined in a razor under WebUI. But the render result is empty. Is iframe supported in this preview version?

Thanks a lot for your help!

**Comment by pietrodicaprio** [comment]
Would be nice to have a sample code of how you're loading the iframe.
Are you opening an external website that contains the iframe? Are you opening a local file? Did you check the developer console for error/warning?
Provide some context, information, steps you performed...

**Comment by Eilon** [comment]
Also, which OS/platform is this on? We don't specifically block IFrame but there might be some limitations around it.

**Comment by jameslin0312** [comment]
The iframe fragment is as below. I am trying this on iOS.

<iframe src="https://www.w3schools.com" title="W3Schools Free Online Web Tutorials"></iframe>

**Comment by pietrodicaprio** [comment]
@jameslin0312 we are still missing a code snippet of how you're loading that iframe. How did you put it into the webview?
Provide the app's code removed of sensitive data but keep the main structure that shows how's working

**Comment by jameslin0312** [comment]
I am testing hybrid app and simply replaced the index.razor under WebUI\Pages as:

@page "/"
<h1>Hello, world!</h1>
<iframe src="https://www.w3schools.com" title="W3Schools Free Online Web Tutorials"></iframe>

**Comment by pietrodicaprio** [comment]
> I am testing hybrid app and simply replaced the index.razor under WebUI\Pages as:
> 
> @page "/"
> 
> # Hello, world!
> <iframe src="https://www.w3schools.com" title="W3Schools Free Online Web Tutorials"></iframe>

Ok, so you are not loading the iframe code in a webview. You are loading it as content of the Blazor page that is then loaded by the BlazorWebView.
If you use the developer console, as I suggested, you can see that the issue is:
> Refused to display 'https://www.w3schools.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
Did you try with a different website? (that is not having that header set to 'sameorigin') I did and is working both on Android and iOS 🙂

**Comment by jameslin0312** [comment]
Many thanks for your help! It works fine if I change the src to another website. But I can't set the element as full size even I set iframe with style of height:100% and all views in Main.razor with VerticalOptions="LayoutOptions.FillAndExpand".

**Comment by pietrodicaprio** [comment]
I'm quite sure you **need** to use CSS to have a borderless full screen iframe.
To be honest I'm not sure this is accepted by the Apple Store TOS anyway. It depends on what you're doing

**Comment by jameslin0312** [comment]
I used Cordova before and have submitted our app successfully to the Apple Store. It's similar of using WebView or iframe to  build hybrid app, but easier to handle native function calls. By the way, how to open "developer console" in VS.Net on Windows 10?

**Comment by pietrodicaprio** [comment]
You can find the steps on the official doc: https://docs.microsoft.com/en-us/mobile-blazor-bindings/advanced/debug-hybrid-apps
Many messages are forwarded to the “output” window of Visual Studio too.

**Comment by jameslin0312** [comment]
Many thanks for your information. It helps a lot!
