### ISSUE TITLE
Cyrillic support issue - BlazorHybridApp

### ISSUE THREAD

**Issue by Slevya** [xamarin/MobileBlazorBindings#315]
FirstBlazorHybridApp - it is masterpiece for blazor developers <3, but we faced the problem of Cyrillic support

Can you help in that situation? 

Cyrillic text: "Привет мир"

![cyr](https://user-images.githubusercontent.com/42978583/106547015-93f6da80-6536-11eb-9fb5-e353e6a2c574.jpg)

Note:  in Hybrid.Android / wwwroot/ index.html, outside < app > tag  cyrrilic text working

**Comment by Slevya** [comment]
It is enough to convert .razor files to UTF-8

**Comment by Eilon** [comment]
Yup that sounds right!
