### ISSUE TITLE
Add support for hosting Blazor Web components directly in Windows Forms (.NET Core)

### ISSUE THREAD

**Issue by Eilon** [xamarin/MobileBlazorBindings#317]
Did you think we forgot about Windows Forms (WinForms)? After doing WPF in #313, let's get Blazor Web working in Windows Forms too!

**Comment by 199621616** [comment]
@Eilon  你太棒了，看到MoileBlazorBindings天天在进步，真高兴

**Comment by Eilon** [comment]
WinForms sample app is here: https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/WinFormsBlazorSample

And it uses this standard Razor Class Library (RCL) as its web content: https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/SharedProjects/RazorClassLibrarySample
