### ISSUE TITLE
Released date and Supporting CSS questions

### ISSUE THREAD

**Issue by AhmedAbuelnour** [xamarin/MobileBlazorBindings#35]
I'm so happy to see such of project is under development, i have some questions, 

- Is this project is planned to be released with .NET 5? 

- Is this going to be the final name for the project? because i think it will make more sense to just drop "Bindings" name.

- Do i need to download Xamarin workload to start using "Mobile Blazor"? 

- Does it allow me to use full CSS? like including bootstrap and using it in styling? 

Thanks in advanced

**Comment by Eilon** [comment]
Great questions and thanks for checking this out!

> * Is this project is planned to be released with .NET 5?

Not currently planned. This project is in an experimental stage so we're looking for feedback on it to help set the direction. Please let us know your thoughts!

> * Is this going to be the final name for the project? because i think it will make more sense to just drop "Bindings" name.

Not the final name. Just a temporary name while we _experiment_ 😄 

> * Do i need to download Xamarin workload to start using "Mobile Blazor"?

Yes you need the Xamarin workload. This project builds on top of Xamarin and Xamarin.Forms to render the UI, and you'll need to be able to run it in the emulator/simulator and/or deploy to a physical Android or iOS device. These are all features that come with the Xamarin Mobile Workload. Check out the [Getting Started](https://docs.microsoft.com/en-us/mobile-blazor-bindings/get-started) steps for details and tutorials.

> * Does it allow me to use full CSS? like including bootstrap and using it in styling?

CSS support is in progress right now. There is some minimal support for CSS (courtesy of Xamarin.Forms) and we are looking to expand it significantly.

**Comment by AhmedAbuelnour** [comment]
Thanks for your quick respond, and yes i really liked the idea of this project, wish to use it in production ;)

**Comment by Hantse** [comment]
About the CSS support, you planify the possibility to use .css file inside the project to drive the UI design ? 

Actually, using simple style or class in element, application is blank, but i suppose is normaly.

Kind regards,

**Comment by Eilon** [comment]
Hi @Hantse , the Weather App sample shows how to include a CSS file:

https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/MobileBlazorBindingsWeather/MobileBlazorBindingsWeather

But with the current code, only limited parts of CSS work. There are some super smart folks working on much better CSS support.

**Comment by srigden2** [comment]
Good this is coming along.

In its current release can you confirm whether or not CSS class selectors are supported and what the usage should be.

I have this button:

`<Button StyleClass="testclass" Text="Test Button"/>`

And the following doesn't work:

`.testclass { background-color: red; }`

However the CSS is being applied as the following works fine:

`button { background-color: red; }`

So either I'm not using the class selectors properly or maybe it isn't supported yet? Thanks for any help.

**Comment by Eilon** [comment]
Great news! If you use Xamarin.Forms 4.5 then I think CSS should fully work! Use this package: https://www.nuget.org/packages/Xamarin.Forms/

So just update all your projects in the solution to use the latest Xamarin.Forms, and then CSS selectors by class, id, and type, should all work!

**Comment by Eilon** [comment]
I will update the sample and docs to reflect this.

**Comment by srigden2** [comment]
That's awesome news, will give that a go real soon! Thanks

**Comment by srigden2** [comment]
Just done a quick initial test and my button example above now works (class selector). Will continue to style the rest of the app and let you know if I find any blockers. Thanks again.

**Comment by Eilon** [comment]
I updated the Weather App sample to use CSS for nearly all the styles. See the change here: https://github.com/xamarin/MobileBlazorBindings/commit/6f11e0195b09db5158db6308f66bec3fc6bc930c?diff=unified

I'm closing this issue now that there's rich CSS support, and I believe the other questions in the thread have been answered.
