### ISSUE TITLE
Support for Cupertino,Fluent,Material UI Component and Custom Controls Cross Platform

### ISSUE THREAD

**Issue by sps014** [xamarin/MobileBlazorBindings#36]
Is there a way to use Cupertino widget with MobileBlazor binding on Android just like a Flutter?
Is it planned?
When will Sliders, Progress Bars will be implemented?
Please have a big team working on this technology, its good and in future will Web, Win UI will be supported ??
 Like Uno Drop the Bindings Name, please ...
That was too much to ask ...
Really Love Blazor Mobile  Technology, good luck and please make it real.

**Comment by Eilon** [comment]
Thanks for the feedback! We're planning on adding Slider and ProgressBar very soon! As for the rest, we don't have specific plans around those, but we're looking for feedback from people like you to help set the direction.

Oh, and as for the name, it's in an early experimental stage, so the name is experimental as well :smile:

I'll update this issue when these controls are added.

**Comment by sps014** [comment]
Thanks, really enjoyed your session yesterday.
