### ISSUE TITLE
Entry Control text property not bound to Component?

### ISSUE THREAD

**Issue by fred-perkins** [xamarin/MobileBlazorBindings#37]
I've been playing around with the Bindings example and tried to make a simple Todo App and run into an issue with the Entry component in the bindings library. 
It seems the Text property of the control isn't bound to underlying control properly. 
To access text I had to do something like so:
```
var control = ((EntryHandler)InputElement.ElementHandler).EntryControl;
string todo = control.Text;
control.ClearValue(Xamarin.Forms.Entry.TextProperty);
```
Naturally this means accessing the underlying control which i'd rather not do :)

Is this a known issue?

**Comment by fred-perkins** [comment]
Sample of the file: [SampleComponent.razor](https://gist.github.com/fred-perkins/6e1e148355884ef4b56cf0414fd2fcbf)

**Comment by Eilon** [comment]
Hi @fred-perkins this sounds like you want a two-way binding in Razor, which is done with `@bind-Text="someField"`.

See the todo sample here with the two-way binding:

https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoList.razor#L7

And here's the field it's using:

https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoList.razor#L45

And here's where it's using/setting the value:

https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoList.razor#L65-L67

Let me know if this works for you!

**Comment by fred-perkins** [comment]
I'll give it a go once I'm back at work tomorrow. Thanks for the info!

**Comment by fred-perkins** [comment]
That's worked perfectly. Closing ticket :)

**Comment by Eilon** [comment]
Awesome!
