### ISSUE TITLE
Is code behind supported?

### ISSUE THREAD

**Issue by tleylan** [xamarin/MobileBlazorBindings#46]
BTW Is this the place to ask questions? I wanted to be sure that code behind for components was supported. It appears to have worked in the case of my HelloWorld.razor.cs file. And I assume these are subclasses of ComponentBase?

Thanks.

**Comment by Eilon** [comment]
Hi @tleylan , this is indeed the place!

You can have a `*.razor.cs` file with a partial class starting in .NET Core 3.1.

Check out these posts to learn a bit more:

* Using a partial class: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#partial-class-support
* Using a code behind class: https://www.telerik.com/blogs/using-a-code-behind-approach-to-blazor-components

I think both techniques work but I haven't tried either yet. If you try it out, let us know what you find!

Thanks,
Eilon

**Comment by tleylan** [comment]
Thanks. I use it Blazor I wasn't certain it worked in MobileBlazorBindings (it does).

**Comment by Eilon** [comment]
Awesome, thank you for confirming!
