### ISSUE TITLE
Failed to build from Source

### ISSUE THREAD

**Issue by sps014** [xamarin/MobileBlazorBindings#56]
Here I am building the app from Source.
When I try to run the app, I am greeted with the following errors. I really don't have any idea about these errors and even line number is not mentioned nor the file name or any hint is provided.

![Screenshot (1)](https://user-images.githubusercontent.com/45932883/72920662-c391d500-3d6f-11ea-9f01-083b00e18ce0.png)

#### steps I followed:
1. cloned repo
2. run int.cmd and run pack.cmd
4. open the solution file 
5. selected the HelloWorldAndroidProject.

**Comment by Eilon** [comment]
Very odd, I've never seen this error before. I will take a look.

**Comment by 0x414c49** [comment]
@sps014 isn't it related to the folder you cloned the project?

**Comment by sps014** [comment]
> @sps014 isn't it related to the folder you cloned the project?

It does not seem so because it is cloned at "C:\Users\Shivendra\Desktop\test\MobileBlazorBindings", it seems a valid path.

**Comment by 0x414c49** [comment]
@sps014 Could you try `dotnet build` in command-line and see what happens? And share the logs also please.

**Comment by sps014** [comment]
# Got this error:


Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\Shivendra\Desktop\test\MobileBlazorBindings\samples\MobileBlazorBindingsHelloWorld\MobileBlazorBindingsHelloWorld.Android\MobileBlazorBindingsHelloWorld.Android.csproj(96,2): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.0.102\Xamarin\Android\Xamarin.Android.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Build FAILED.

C:\Users\Shivendra\Desktop\test\MobileBlazorBindings\samples\MobileBlazorBindingsHelloWorld\MobileBlazorBindingsHelloWorld.Android\MobileBlazorBindingsHelloWorld.Android.csproj(96,2): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.0.102\Xamarin\Android\Xamarin.Android.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.07


![error](https://user-images.githubusercontent.com/45932883/73119283-9dde1900-3f85-11ea-93fd-1d688bf3ad2f.PNG)

**Comment by Eilon** [comment]
Unfortunately `dotnet build` doesn't work because the CSharp Android targets don't seem to be compatible with .NET Core. So, you have to use regular MSBuild to build. It's an unfortunate limitation that will hopefully eventually be resolved. You can still build the NuGet packages with .NET Core, but not the sample apps.

**Comment by sps014** [comment]
With the new release, it got fixed, thanks, everyone.
