### ISSUE TITLE
Multi-direction support for Visual Element (RTL, LTR)

### ISSUE THREAD

**Issue by 0x414c49** [xamarin/MobileBlazorBindings#58]
In Xamarin Forms, every `VisualElement` has a property called [`FlowDirection`](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.flowdirection?view=xamarin-forms).

In MobileBlazorBindings, we need to expose this property to make it more multi-cultural. 

This is an example:

```
<TabbedPage FlowDirection="FlowDirection.RightToLeft">
    <ContentPage Title="Todo">
        <StackLayout>
            <Label FontSize="20" TextColor="Color.Crimson" Text="Todo Items" HorizontalTextAlignment="TextAlignment.Center" />
            <TodoList />
        </StackLayout>
    </ContentPage>
    <ContentPage Title="Counter">
        <Counter />
    </ContentPage>
    <ContentPage Title="About">
        <About />
    </ContentPage>
</TabbedPage>
```

I think if we only expose the attribute, the Multi-Direction issue will be solved by Xamarin Forms itself:

> The default value of FlowDirection for a visual element that has no parent is LeftToRight, even on platforms where FlowDirection is RightToLeft. Therefore, developers must deliberately opt in to right-to-left layout. Developers can choose right-to-left layout by setting the FlowDirection property of the root element to RightToLeft to chosse right-to-left layout, or to MatchParent to match the device layout.
> 
> All VisualElements that have a parent default to MatchParent.

An example of RTL page:
![Screenshot_1579775303](https://user-images.githubusercontent.com/57097646/72977773-7cd6c600-3dd5-11ea-80b9-9235f5eb88e0.png)

**Comment by Eilon** [comment]
Fixed in https://github.com/xamarin/MobileBlazorBindings/pull/59. Thanx!
