### ISSUE TITLE
Label does not update when variable is set from an event.

### ISSUE THREAD

**Issue by CipherLab** [xamarin/MobileBlazorBindings#60]
It's simple to replicate. Create an event handler and update a string variable which is tied to a label in the razor page. The label will not update. 
If you throw a button on the page and update the variable with a += ""; the label will update with the data.

**Comment by Eilon** [comment]
Hi @CipherLab can you show a small snippet of code that demonstrates this?

**Comment by CipherLab** [comment]
I did more testing, and it doesn't seem to be events themselves, it seems to be because the event is being invoked on a different thread. In my case the event is from reading an NFC tag in an Android specific class. That event is passing to my own event on an interface that's injected to the razor page. But here's a simple example that also does not work in what I think is the same way (first click will not update the text, but second click will):

`@using System.Diagnostics
@using System.Threading
@inject AppState AppState

<StackLayout>
    <Label FontSize="30" FontAttributes="FontAttributes.Italic" Text="@_test" />
    <Button Text="Test" OnClick="HandleClick" />
</StackLayout>

@code {

    private string _test = "";
    public event EventHandler<GotMessageReceivedEventArgs> GotMessageReceivedEventHandler;
    protected virtual void OnGotMessageReceived(string data)
    {
        GotMessageReceivedEventHandler?.Invoke(this, new GotMessageReceivedEventArgs(data));
    }


    void HandleClick()
    {
       _test += "";
        new Thread(() =>
            Test()
            ).Start();
    }

    protected override void OnInitialized()
    {
        base.OnInitialized();
        this.GotMessageReceivedEventHandler += OnGotMessageReceivedEventHandler;
    }

    private void OnGotMessageReceivedEventHandler(object sender, GotMessageReceivedEventArgs e)
    {
        _test += e.Data;
    }

    private void Test()
    {
        System.Threading.Thread.Sleep(3000);
        OnGotMessageReceived("TEST123");
    }
}
`

**Comment by Eilon** [comment]
If the update to the data is happening on some other thread (say, a callback from some OS/hardware event), then Blazor doesn't know about it, so it won't refresh the UI. Fortunately, there's a way to _tell_ Blazor to update the UI: Call `StateHasChanged()` from the callback. This method is available on every Blazor component and tells Blazor to try to re-render that portion of the UI.

If you could give that a try and let me know if it works, that would be great!

**Comment by CipherLab** [comment]
Ah, yes that does the trick. Thanks. Sorry, thought I found an issue.

**Comment by Eilon** [comment]
No worries. This aspect is certainly a bit tricky when you first see it. But hopefully it gets easy once you know it!
