### ISSUE TITLE
FontSize?

### ISSUE THREAD

**Issue by tleylan** [xamarin/MobileBlazorBindings#73]
I'm trying :-)

I noticed there is a FontSize property on a Label but there doesn't appear to be on a Button. The Xamarin button does have a FontSize (I believe). I'm trying to use Xamarin tutorials as a guide but can't quite figure out how to do similar things with Blazor.

Would my reading all the project source fill in the blanks do you think?

**Comment by Eilon** [comment]
Hi @tleylan thanks for checking out this project! You're not missing anything - some properties were forgotten in the initial release, including `Button`'s `FontSize` property.

I added the missing property (plus several others) in this commit from a few days ago:
https://github.com/xamarin/MobileBlazorBindings/commit/eee7d5fae64befb51ca6a807e02444410caa16fa#diff-68da0bdd265e5970cfdce0e8442e7635R26

We're planning to publish an update next week so stay tuned and we'll have this available very soon!

**Comment by tleylan** [comment]
@Eilon Thanks for the answer and the reassurance that I'm not just old :-) I think I should read through the code a bit more but some of the systems like ASP.Net,, Blazor and such contain so much code it seems that would be all I would have time for.

I am looking forward to the next release.

**Comment by Eilon** [comment]
Reading large code bases can be intimidating, I completely agree. I found it best to learn how the things I directly interact with work. For example, just reading the code of one Mobile Blazor Bindings component (easy). Then perhaps one handler (also easy). Seeing how they interact, where they reference each other, what else they reference, etc. Then, one day, like a year later, it starts to make sense as a system 😉
