### ISSUE TITLE
Field service & Taxi dispatch sample

### ISSUE THREAD

**Issue by papyr** [xamarin/MobileBlazorBindings#84]
Hello, in many cases the samples are not through to get self help since they don't cover features needed for field applications.

Can you please consider these two samples - 

- [ ] Field service Sample
- [ ] Taxi dispatch sample

**Comment by Eilon** [comment]
Hi @papyr can you provide more info on what these samples are? I'm happy to improve the samples if I can get more info on what you're looking for.

**Comment by papyr** [comment]
Couple samples :
[Sample 1](http://bit.ly/31QfdJJ)
[Features lin](http://bit.ly/39zweuh)k - Known as FSM Field Service Management

- [ ] 1. Job Scheduling and Dispatching
- [ ] 2. Work Order Management
- [ ] 3. Mobile Access
- [ ] 4. Parts Inventory Management
- [ ] 5. Case, Contact and Order Management
- [ ] 6. Reporting and Analytics
- [ ] 7. Messaging
- [ ] 8. Route Planning and GPS Integration
_______________________________

[uber clone sample](http://bit.ly/2Sny37I)
https://github.com/SimCoderYoutube/UberClone

- [ ] Social Media Sign up and Login
- [ ] Backend API to call complete transactions
- [ ] Rider can signup and login immediately through their social media account along with email and password option
- [ ] Book Now or Schedule Trip
- [ ] Rider can book their trip immediate or they can schedule It as per their requirement.
- [ ] Real-Time Tracking
- [ ] Riders can track service providers’ real-time geolocation on google map with details of ETA and the ability to call driver option.
- [ ] Online Payment
- [ ] Rider can pay their service charge through in-app wallet or card (Debit / Credit). Even they can select cash on service option.
- [ ] Rate and Review
- [ ] Riders can share their trip experience with sharing few thoughts about service and rate service provider on a scale of five stars.
- [ ]     Surge: It allows you to increase the ride fare during busy hours.
- [ ]     Pooling: Just like UberPool, Tookan Taxi allows ride pooling in order to save riders money.
- [ ]     Scheduled rides: With this feature customer can schedule rides for the future.
- [ ]     Payment integrations: Tookan allows your customer to pay via multiple payment options like cash, credit cards and payment gateways like Stripe, Paypal etc. Similarly, you can automate the driver earning using Stripe Connect.
- [ ]     Geofencing: Geofencing allows you to divide your workforce region-wise, allowing your drivers to receive rides only in their geofence.
- [ ]     Recurring rides: It’s an upcoming feature where the customer will be able to book recurring rides at once by setting a recurring rule.
- [ ]     Multiple offerings: Businesses having multiple offerings like a delivery service and taxi ride can have both of the offerings in one app.

**Comment by chrisevans9629** [comment]
I think perhaps a better idea would be to convert some samples that xamarin already has?  For example the [pretty weather app](https://github.com/jamesmontemagno/app-pretty-weather) or the [xamarin CRM sample](https://github.com/xamarin/app-crm)

**Comment by papyr** [comment]
Hi @Eilon @chrisevans9629 if you want to repurpose those its a quick start. However, just be aware that those samples dont have the main practical uses cases on what functional features are used.

Thats the reason I went through the pains taking process of just narrowing down some core items in the list above. The other features I was able somehow look from the other samples. Ultimately this will serve as a good example for futures developers in one place.

**Comment by Eilon** [comment]
Thanks for the suggestions, I will take a look at these.

BTW the Pretty Weather app is already a sample:

* Source code: https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/MobileBlazorBindingsWeather
* Documentation: https://docs.microsoft.com/mobile-blazor-bindings/walkthroughs/weather-app

**Comment by papyr** [comment]
Hello any update on this?

**Comment by Eilon** [comment]
Hi @papyr , the request here is for a substantial sample that we don't currently have planned. But we have several smaller samples within this repo in the [samples](https://github.com/xamarin/MobileBlazorBindings/tree/master/samples) folder. I have also written an app that is available in the Apple App Store for tracking recipes, which is available at the [Rezipe](https://github.com/Eilon/Rezipe) repo. We are working on more samples as well.

**Comment by papyr** [comment]
Thats a bummer, can you tell me how to do the core Taxi features for routing, dispatch, scheduling and tracking or which samples have that functionality. The weather one does not have this.

**Comment by Eilon** [comment]
@papyr I'm sorry that's not something I can provide. That might be better suited for hiring a consultant who can offer such services. If you're having any _specific_ technical problems, or if you find a bug, or have a feature suggestion, this would be a great place to post it.
