### ISSUE TITLE
Checkbox , Switch components issues with nullable boolean

### ISSUE THREAD

**Issue by tranpl** [xamarin/MobileBlazorBindings#85]
Playing around with the preview, looks promising. I was unable to compile when using a nullable type (bool?). Works fine if i use normal bool. Getting a CS0104,
message: 'Button' is an ambiguous reference between 'Microsoft.MobileBlazorBindings.Elements.Button' and 'Xamarin.Forms.Button'
This happens on the @bind-IsToggle or @bind-IsChecked attribute for (Switch and Checkbox components respectively).

Using Preview 2 (0.2.42-preview)

Thank you for this awesome project.

**Comment by Eilon** [comment]
Hi @tranpl , the "ambiguous reference" error can be ignored. It is a known issue that is tracked here: https://github.com/xamarin/MobileBlazorBindings/issues/49

Even though the `CheckBox` and `Switch` components have a `bool?` (nullable bool) property for their values, they should be set only to `true` or `false`. A `null` value means "property not set", which I think is equivalent to un-checked. I don't think the CheckBox or Switch control support tri-state checkboxes.

Thank you so much for checking out Mobile Blazor Bindings!

**Comment by Eilon** [comment]
Closing this because I think everything that's a bug is covered elsewhere. Please let me know if I'm mistaken and we can follow up on details. Thank you!
