### ISSUE TITLE
Investigate support for Blazor / Xamarin.Forms routing

### ISSUE THREAD

**Issue by Eilon** [xamarin/MobileBlazorBindings#86]
Stuff to look at:
* Xamarin.Forms Shell supports routing
* Blazor has an `@page` directive and various routing concepts

**Comment by saint4eva** [comment]
Kindly use the @page directive for routing. Thank you.

**Comment by dev-fJ-del** [comment]
@saint4eva how do you navigate?
I've injected NavigationManager
`@inject NavigationManager navManager`
and on
`navManager.NavigateTo("/views/provinces")`
But the app just shows a blank screen then(Android)

**Comment by Eilon** [comment]
@dev-fJ-del currently there is no proper navigation support at all within a Mobile Blazor Bindings app unless you call directly into Xamarin.Forms APIs. But it's not integrated at all with Blazor pages or navigation (yet!).

**Comment by lachlanwgordon** [comment]
I'm keen to have a crack at implementing this. My thoughts so far are:
* The overall goal is to have navigation in Mobile Blazor Binding work exactly the same as it does in Blazor Web.
    * As @saint4eva suggests, routes should be declared on each page with @page "/url"
    * From a code you will call NavigationManager.NavigateTo("url");
* Shell will be used for initial implementation
    * MasterDetail/Tabbed/NavigationPage could be considered for additional implementations in the future
    * Shell supports URI navigation, but uses query strings which we'll need to work around
    * Supports tabs and flyout out of the box

@Eilon or anyone else have suggestions about this, or reasons why I shouldn't go ahead with it?

**Comment by lachlanwgordon** [comment]
Further Research Findings:
* Shell navigation required Routes to be registered in the Routing static class
* Shell Routing is very powerful and complex, Shane has thought of a lot of situation and edge cases, and this has been through a lot of testing an refinement. Using this rather than rolling our own MBB Navigation would be excellent if we can get it working.
* Getting a list of all Components that use as @page directive is fairly easy
* Registering a route with XamarinForms Routing can be done based on components with @page

Unanswered problems:
* The difference between a XamarinForms ContentPage and a MobileBlazorBinding ContentPage is still a bit confusing to me.
    * If I register a Route with a MBB ContentPage, Shell can't navigate to it, because it's not a nXF.Page
    * How does Current MBB Shell deal with this, somehow it accepts an MBBPage into a Shell with would otherwise need an XFPage
    * Could we consider having MMBContentPage extend XFContentPage, so they can be used interchangeably?
*Still not sure how to handle route parameters give Shell always assumes any `/` separate string is part of a string rather than a parameter.

You can see my experimenting in a branch in my fork, https://github.com/lachlanwgordon/MobileBlazorBindings/tree/Navigation, but the code there is pretty messy while i'm experimenting with stuff.

**Comment by Eilon** [comment]
Hi @lachlanwgordon I'd love for you to have a crack at this!

> * If I register a Route with a MBB ContentPage, Shell can't navigate to it, because it's not a nXF.Page

How did you register the route? The MBB Elements are representations of the `<tags>` in the .razor file, which are then used to "render out" special Blazor content that later is handled by the matching handler. That matching handler then creates the Xamarin.Forms component. I talk a bit about this in the advanced docs: https://docs.microsoft.com/mobile-blazor-bindings/advanced/access-native-controls

> * How does Current MBB Shell deal with this, somehow it accepts an MBBPage into a Shell with would otherwise need an XFPage

Like all other MBB items, the stuff you type into the .razor file gets processed and at runtime it creates XF components. An MBB component _handler_ knows who its parent _handler_ is, so when you add an MBB ShellItem to an MBB Shell (or whatever), the MBB ShellItemHandler checks its parent, sees it's an MBB Shell, then from the MBB Shell it gets the XF Shell, so that when it creates its XF ShellItemHandler, it can add it to the XF Shell. Easy as 3.14159 😄 

> * Could we consider having MMBContentPage extend XFContentPage, so they can be used interchangeably?

This is not possible because each has requirements on what its base class must be. Also, they represent different concepts. You can get from MBB items to the XF items via the `NativeControl` property on every MBB item, such as MBB's ContentPage:

https://github.com/xamarin/MobileBlazorBindings/blob/master/src/Microsoft.MobileBlazorBindings/Elements/ContentPage.generated.cs#L20

I'm happy to do another call to dive into this. It's not an easy problem to solve, but I think after some breakthroughs, this could be super cool!

**Comment by lachlanwgordon** [comment]
> How did you register the route?

I scan the assembly for all PageAttributes. Then register them using Routing.RegisterRoute(). This is how explicit routes are registered using XF Shell. By convention we usually make the call to Routing in the Shell's code behind but it's a `public static` class that anyone can call from anywhere.

```
private void FindRoutes(Assembly assembly)
{
    var pages = assembly.GetTypes().Where(x => x.GetCustomAttributes<RouteAttribute>().Any());
    foreach (var page in pages)
    {
        var routes = page.GetCustomAttributes<RouteAttribute>();
        foreach (var route in routes)
        {
            //page will be an MBB page, but shell wants an XFPage.
            //When you try to use this route in navigation it will silently fail 
            XF.Routing.RegisterRoute(route.Template, page);
        }
    }
}
```

I'm guessing something equivalent but better already exists in ASP.NET Core. If that code has a suitable API surface I can hopefully call into it instead.

Thanks for clarification on types, I mostly get it, until I get to a call that needs one and I have the other and the conversion is out of my control.

Keen for a chat, let's work that out by email.

**Comment by lachlanwgordon** [comment]
Looks like the overload for RegisterRoute that takes a factory instead of a type could solve my XF.Page/MBBPage conflict.

**Comment by Eilon** [comment]
Super HUGE thank you to @lachlanwgordon for sending an AWESOME pull request that implements this! I had several great chats with @lachlanwgordon and he put up with all my code review feedback too 😄

**Comment by lachlanwgordon** [comment]
This was great fun, thanks for all your help @Eilon.

**Comment by Eilon** [comment]
You did all the hard work! https://twitter.com/original_ejl/status/1290508342410936321
