### ISSUE TITLE
Navigate to new Page

### ISSUE THREAD

**Issue by RicardoDev1999** [xamarin/MobileBlazorBindings#89]
Hi, I am currently looking at this solution to make a little demo to show on my company.
But I was trying to do a navigation to another ContentPage and I didn't find any documentation on this.
Is this implemented in any way?

**Comment by Eilon** [comment]
Hi @RicardoDev1999 , there's support for loading a modal dialog, which is a form of navigation. Check out the todo sample here: https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/MobileBlazorBindingsTodoSample

In particular, check out the `ModalContainer` component as seen here: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoEntry.razor#L12-L14

And the related code in that file. And then check out the dialog that it launches here: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoEntryDetails.razor

Please let me know if you have any questions!

**Comment by RicardoDev1999** [comment]
Thanks :)
Keep up the good work!

Cheers
