### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by DAMcK-TREC** [xamarin/MobileBlazorBindings#94]
Using Microsoft Visual Studio Professional 2019
Version 16.4.5
.Net Standard v2.0.3
All NuGet packages at latest revisions

Can not resolve reference: `Microsoft.Bcl.AsyncInterfaces`, referenced by `System.Text.Json`. Please add a NuGet package or assembly reference for `Microsoft.Bcl.AsyncInterfaces`, or remove the reference to `System.Text.Json`.	MobileBlazorBindingsHelloWorld.Android	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1808	

an not resolve reference: `Microsoft.Bcl.AsyncInterfaces`, referenced by `System.Text.Json`. Please add a NuGet package or assembly reference for `Microsoft.Bcl.AsyncInterfaces`, or remove the reference to `System.Text.Json`.	MobileBlazorBindingsHelloWorld.Android	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1808

**Comment by Eilon** [comment]
Hi this looks like a duplicate of https://github.com/xamarin/MobileBlazorBindings/issues/70, so closing this issue. Thanks!
