### ISSUE TITLE
todo-app walkthrough steps confusing

### ISSUE THREAD

**Issue by nickkfwong** [xamarin/MobileBlazorBindings#95]
In step 4, the below is mentioned : 
> Change the code in App.cs to reference the new TodoApp component instead of HelloWorld:
> `host.AddComponent<TodoApp>(parent: this);`

I think it is better to state explicitly to also remove the line:
`MainPage = new ContentPage();`

I confirmed this by looking at the sample code provided [here](https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/App.cs)

It spent me some time for figuring out the reason why an empty page is opened.
I am new to xaramin and android and clearer steps (esp the document is describing how to change the app from the HelloWorld sample into the Todo one) would definitely be helpful to any other people like me. (well I should look into the source earlier)

**Comment by Eilon** [comment]
Hi @nickkfwong thank you for reporting this! The doc is indeed out of date. It was correct for Preview 1 but some changes in Preview 2 have caused the doc to be slightly incorrect. I will update this ASAP. Glad you got it working!

**Comment by Eilon** [comment]
I took another look at this and made some updates to the doc that I hope will be published later this month.

The suggested code change was mostly correct, but I am making some updates to the docs to be more accurate with regard to the steps to take.
