### ISSUE TITLE
Mobile Blazor with Flutter

### ISSUE THREAD

**Issue by ansarizafar** [xamarin/MobileBlazorBindings#97]
Steve Sanderson had showed a demo of a blazor desktop app with flutter at NDC conference https://youtu.be/uW-Kk7Qpv5U?t=3300. Is There any plan to add support for Flutter components?

**Comment by Eilon** [comment]
Hi @ansarizafar I'm familiar with @SteveSandersonMS 's project but I'm not aware of any plans to bring the Blazor + Flutter any further.

@SteveSandersonMS - do you have anything further to share on this?

**Comment by ansarizafar** [comment]
Native components are limited and difficult to style. Flutter has a huge set of easy to use and beautiful ui components as Flutter controls every pixel and draw its own components on canvas. Flutter components are also cross platform. I suggest Mobile blazor team to consider flutter + blazor integration or use Flutter's approach to build a set of flutter like components using SkiaSharp. Xamarin form components are not enough for building beautiful mobile apps.

**Comment by ansarizafar** [comment]
@Eilon I have just found this new C# cross platform ui framework https://github.com/Clancey/Comet Comet is using a SwiftUI like approach. Please have a look.

**Comment by Eilon** [comment]
Hi @ansarizafar we're looking at several options for people to get the experiences they want in mobile apps. I work with @Clancey and have discussed Comet with him before. We're all collaborating on mobile app dev to come up with some exciting stuff!

**Comment by ansarizafar** [comment]
I am excited about Comet. I think Comet (like flutter) is much better than Blazor/Xamarin.

**Comment by Eilon** [comment]
This is useful feedback, thank you for sharing! I will share this with my colleagues. I'm closing this issue because there's no further action required here. Please let me know if you have any further feedback.
