### ISSUE TITLE
Investigate dual-screen support

### ISSUE THREAD

**Issue by Eilon** [xamarin/MobileBlazorBindings#99]
What's needed?
* New TwoPaneView control with Pane1 and Pane2 that wraps the [Xamarin.Forms TwoPaneView](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.dualscreen.twopaneview?view=xamarin-forms)
* Samples
* Docs

PR to add initial support here: https://github.com/xamarin/MobileBlazorBindings/pull/147
Demo Razor file: https://gist.github.com/Eilon/c7aacf1b15b6035a2211dd33ae08d7ca

Resources to get started:
* Docs: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dual-screen/design-patterns
* Use this package: https://www.nuget.org/packages/Xamarin.Forms.DualScreen/
* Blog info: https://devblogs.microsoft.com/xamarin/xamarin-goes-dual-screen/

**Comment by conceptdev** [comment]
Sample code: https://github.com/microsoft/surface-duo-sdk-xamarin-samples/tree/master/XamarinForms
Newer blog: https://devblogs.microsoft.com/xamarin/surface-duo-surface-neo-with-xamarin-forms/
🙂

**Comment by Eilon** [comment]
Awesome thank you for the additional pointers!

**Comment by Eilon** [comment]
Well I got it working with a wrapper for `TwoPaneView` but there seem to be some funky bugs. More to come.

![image](https://user-images.githubusercontent.com/202643/82365956-45b0a400-99c6-11ea-81f4-7ad36acf3214.png)

**Comment by Eilon** [comment]
Other links of note (found through the above links):

* Xamarin.Forms Sample: https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/DualScreenDemos
* Setting up Surface Duo emulator: https://docs.microsoft.com/en-us/dual-screen/android/use-emulator?tabs=csharp%2Cwindows#xamarin-developers

**Comment by conceptdev** [comment]
Can we help? Happy to play around with the wrapper...

**Comment by Eilon** [comment]
I'm cleaning up and old branch I had that I never pushed to GitHub. I might just merge what I have into the main branch as an additional experiment. That way it won't get quite so stale.

**Comment by Eilon** [comment]
OK here's a PR to add initial DualScreen support. [Sample code here](https://github.com/xamarin/MobileBlazorBindings/pull/147#issuecomment-663232128).

It's a bit wonky, but it's good enough as a starting point for investigation.

@conceptdev let me know if you play with this and if there's anything you'd like to look into. I'm happy to offer assistance however I can!

**Comment by Eilon** [comment]
I'm closing this issue because the DualScreen NuGet package ships now and I don't think there's much else to do right now from a Mobile Blazor Bindings perspective. If I'm wrong about that, please file a new issue!
